{-# LANGUAGE MultiWayIf #-}
-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.
{-# LANGUAGE OverloadedStrings #-}

-- | Contains the types generated from the schema AuthenticatorSMSChallengeResponseRequest
module AuthentikAPI.Types.AuthenticatorSMSChallengeResponseRequest where

import qualified AuthentikAPI.Common
import AuthentikAPI.TypeAlias
import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Functor
import qualified Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe

-- | Defines the object schema located at @components.schemas.AuthenticatorSMSChallengeResponseRequest@ in the specification.
--
-- SMS Challenge response, device is set by get_response_instance
data AuthenticatorSMSChallengeResponseRequest = AuthenticatorSMSChallengeResponseRequest
  { -- | code
    authenticatorSMSChallengeResponseRequestCode :: (GHC.Maybe.Maybe GHC.Types.Int),
    -- | component
    --
    -- Constraints:
    --
    -- * Minimum length of 1
    authenticatorSMSChallengeResponseRequestComponent :: (GHC.Maybe.Maybe Data.Text.Internal.Text),
    -- | phone_number
    --
    -- Constraints:
    --
    -- * Minimum length of 1
    authenticatorSMSChallengeResponseRequestPhoneNumber :: (GHC.Maybe.Maybe Data.Text.Internal.Text)
  }
  deriving
    ( GHC.Show.Show,
      GHC.Classes.Eq
    )

instance Data.Aeson.Types.ToJSON.ToJSON AuthenticatorSMSChallengeResponseRequest where
  toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("code" Data.Aeson.Types.ToJSON..=)) (authenticatorSMSChallengeResponseRequestCode obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("component" Data.Aeson.Types.ToJSON..=)) (authenticatorSMSChallengeResponseRequestComponent obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("phone_number" Data.Aeson.Types.ToJSON..=)) (authenticatorSMSChallengeResponseRequestPhoneNumber obj) : GHC.Base.mempty))
  toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("code" Data.Aeson.Types.ToJSON..=)) (authenticatorSMSChallengeResponseRequestCode obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("component" Data.Aeson.Types.ToJSON..=)) (authenticatorSMSChallengeResponseRequestComponent obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("phone_number" Data.Aeson.Types.ToJSON..=)) (authenticatorSMSChallengeResponseRequestPhoneNumber obj) : GHC.Base.mempty)))

instance Data.Aeson.Types.FromJSON.FromJSON AuthenticatorSMSChallengeResponseRequest where
  parseJSON = Data.Aeson.Types.FromJSON.withObject "AuthenticatorSMSChallengeResponseRequest" (\obj -> ((GHC.Base.pure AuthenticatorSMSChallengeResponseRequest GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "code")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "component")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "phone_number"))

-- | Create a new 'AuthenticatorSMSChallengeResponseRequest' with all required fields.
mkAuthenticatorSMSChallengeResponseRequest :: AuthenticatorSMSChallengeResponseRequest
mkAuthenticatorSMSChallengeResponseRequest =
  AuthenticatorSMSChallengeResponseRequest
    { authenticatorSMSChallengeResponseRequestCode = GHC.Maybe.Nothing,
      authenticatorSMSChallengeResponseRequestComponent = GHC.Maybe.Nothing,
      authenticatorSMSChallengeResponseRequestPhoneNumber = GHC.Maybe.Nothing
    }
