{-# LANGUAGE MultiWayIf #-}
-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.
{-# LANGUAGE OverloadedStrings #-}

-- | Contains the types generated from the schema FlowLayoutEnum
module AuthentikAPI.Types.FlowLayoutEnum where

import qualified AuthentikAPI.Common
import AuthentikAPI.TypeAlias
import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Functor
import qualified Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe

-- | Defines the enum schema located at @components.schemas.FlowLayoutEnum@ in the specification.
data FlowLayoutEnum
  = -- | This case is used if the value encountered during decoding does not match any of the provided cases in the specification.
    FlowLayoutEnumOther Data.Aeson.Types.Internal.Value
  | -- | This constructor can be used to send values to the server which are not present in the specification yet.
    FlowLayoutEnumTyped Data.Text.Internal.Text
  | -- | Represents the JSON value @"stacked"@
    FlowLayoutEnumEnumStacked
  | -- | Represents the JSON value @"content_left"@
    FlowLayoutEnumEnumContentLeft
  | -- | Represents the JSON value @"content_right"@
    FlowLayoutEnumEnumContentRight
  | -- | Represents the JSON value @"sidebar_left"@
    FlowLayoutEnumEnumSidebarLeft
  | -- | Represents the JSON value @"sidebar_right"@
    FlowLayoutEnumEnumSidebarRight
  deriving (GHC.Show.Show, GHC.Classes.Eq)

instance Data.Aeson.Types.ToJSON.ToJSON FlowLayoutEnum where
  toJSON (FlowLayoutEnumOther val) = val
  toJSON (FlowLayoutEnumTyped val) = Data.Aeson.Types.ToJSON.toJSON val
  toJSON (FlowLayoutEnumEnumStacked) = "stacked"
  toJSON (FlowLayoutEnumEnumContentLeft) = "content_left"
  toJSON (FlowLayoutEnumEnumContentRight) = "content_right"
  toJSON (FlowLayoutEnumEnumSidebarLeft) = "sidebar_left"
  toJSON (FlowLayoutEnumEnumSidebarRight) = "sidebar_right"

instance Data.Aeson.Types.FromJSON.FromJSON FlowLayoutEnum where
  parseJSON val =
    GHC.Base.pure
      ( if
          | val GHC.Classes.== "stacked" -> FlowLayoutEnumEnumStacked
          | val GHC.Classes.== "content_left" -> FlowLayoutEnumEnumContentLeft
          | val GHC.Classes.== "content_right" -> FlowLayoutEnumEnumContentRight
          | val GHC.Classes.== "sidebar_left" -> FlowLayoutEnumEnumSidebarLeft
          | val GHC.Classes.== "sidebar_right" -> FlowLayoutEnumEnumSidebarRight
          | GHC.Base.otherwise -> FlowLayoutEnumOther val
      )
