module AuthentikAPI.Types.GroupSourceConnectionRequest where
import qualified Data.Aeson
import qualified AuthentikAPI.Common
data GroupSourceConnectionRequest
instance Show GroupSourceConnectionRequest
instance Eq GroupSourceConnectionRequest
instance Data.Aeson.FromJSON GroupSourceConnectionRequest
instance Data.Aeson.ToJSON GroupSourceConnectionRequest
