{-# LANGUAGE MultiWayIf #-}
-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.
{-# LANGUAGE OverloadedStrings #-}

-- | Contains the types generated from the schema IdentificationChallengeResponseRequest
module AuthentikAPI.Types.IdentificationChallengeResponseRequest where

import qualified AuthentikAPI.Common
import AuthentikAPI.TypeAlias
import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Functor
import qualified Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe

-- | Defines the object schema located at @components.schemas.IdentificationChallengeResponseRequest@ in the specification.
--
-- Identification challenge
data IdentificationChallengeResponseRequest = IdentificationChallengeResponseRequest
  { -- | captcha_token
    identificationChallengeResponseRequestCaptchaToken :: (GHC.Maybe.Maybe (AuthentikAPI.Common.Nullable Data.Text.Internal.Text)),
    -- | component
    --
    -- Constraints:
    --
    -- * Minimum length of 1
    identificationChallengeResponseRequestComponent :: (GHC.Maybe.Maybe Data.Text.Internal.Text),
    -- | password
    identificationChallengeResponseRequestPassword :: (GHC.Maybe.Maybe (AuthentikAPI.Common.Nullable Data.Text.Internal.Text)),
    -- | uid_field
    --
    -- Constraints:
    --
    -- * Minimum length of 1
    identificationChallengeResponseRequestUidField :: Data.Text.Internal.Text
  }
  deriving
    ( GHC.Show.Show,
      GHC.Classes.Eq
    )

instance Data.Aeson.Types.ToJSON.ToJSON IdentificationChallengeResponseRequest where
  toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("captcha_token" Data.Aeson.Types.ToJSON..=)) (identificationChallengeResponseRequestCaptchaToken obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("component" Data.Aeson.Types.ToJSON..=)) (identificationChallengeResponseRequestComponent obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("password" Data.Aeson.Types.ToJSON..=)) (identificationChallengeResponseRequestPassword obj) : ["uid_field" Data.Aeson.Types.ToJSON..= identificationChallengeResponseRequestUidField obj] : GHC.Base.mempty))
  toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("captcha_token" Data.Aeson.Types.ToJSON..=)) (identificationChallengeResponseRequestCaptchaToken obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("component" Data.Aeson.Types.ToJSON..=)) (identificationChallengeResponseRequestComponent obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("password" Data.Aeson.Types.ToJSON..=)) (identificationChallengeResponseRequestPassword obj) : ["uid_field" Data.Aeson.Types.ToJSON..= identificationChallengeResponseRequestUidField obj] : GHC.Base.mempty)))

instance Data.Aeson.Types.FromJSON.FromJSON IdentificationChallengeResponseRequest where
  parseJSON = Data.Aeson.Types.FromJSON.withObject "IdentificationChallengeResponseRequest" (\obj -> (((GHC.Base.pure IdentificationChallengeResponseRequest GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "captcha_token")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "component")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "password")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "uid_field"))

-- | Create a new 'IdentificationChallengeResponseRequest' with all required fields.
mkIdentificationChallengeResponseRequest ::
  -- | 'identificationChallengeResponseRequestUidField'
  Data.Text.Internal.Text ->
  IdentificationChallengeResponseRequest
mkIdentificationChallengeResponseRequest identificationChallengeResponseRequestUidField =
  IdentificationChallengeResponseRequest
    { identificationChallengeResponseRequestCaptchaToken = GHC.Maybe.Nothing,
      identificationChallengeResponseRequestComponent = GHC.Maybe.Nothing,
      identificationChallengeResponseRequestPassword = GHC.Maybe.Nothing,
      identificationChallengeResponseRequestUidField = identificationChallengeResponseRequestUidField
    }
