module AuthentikAPI.Types.InitialPermissionsModeEnum where
import qualified Data.Aeson
import qualified AuthentikAPI.Common
data InitialPermissionsModeEnum
instance Show InitialPermissionsModeEnum
instance Eq InitialPermissionsModeEnum
instance Data.Aeson.FromJSON InitialPermissionsModeEnum
instance Data.Aeson.ToJSON InitialPermissionsModeEnum
