{-# LANGUAGE MultiWayIf #-}
-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.
{-# LANGUAGE OverloadedStrings #-}

-- | Contains the types generated from the schema MicrosoftEntraProviderRequest
module AuthentikAPI.Types.MicrosoftEntraProviderRequest where

import qualified AuthentikAPI.Common
import AuthentikAPI.TypeAlias
import {-# SOURCE #-} AuthentikAPI.Types.OutgoingSyncDeleteAction
import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Functor
import qualified Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe

-- | Defines the object schema located at @components.schemas.MicrosoftEntraProviderRequest@ in the specification.
--
-- MicrosoftEntraProvider Serializer
data MicrosoftEntraProviderRequest = MicrosoftEntraProviderRequest
  { -- | client_id
    --
    -- Constraints:
    --
    -- * Minimum length of 1
    microsoftEntraProviderRequestClientId :: Data.Text.Internal.Text,
    -- | client_secret
    --
    -- Constraints:
    --
    -- * Minimum length of 1
    microsoftEntraProviderRequestClientSecret :: Data.Text.Internal.Text,
    -- | dry_run: When enabled, provider will not modify or create objects in the remote system.
    microsoftEntraProviderRequestDryRun :: (GHC.Maybe.Maybe GHC.Types.Bool),
    -- | exclude_users_service_account
    microsoftEntraProviderRequestExcludeUsersServiceAccount :: (GHC.Maybe.Maybe GHC.Types.Bool),
    -- | filter_group
    microsoftEntraProviderRequestFilterGroup :: (GHC.Maybe.Maybe (AuthentikAPI.Common.Nullable Data.Text.Internal.Text)),
    -- | group_delete_action
    microsoftEntraProviderRequestGroupDeleteAction :: (GHC.Maybe.Maybe OutgoingSyncDeleteAction),
    -- | name
    --
    -- Constraints:
    --
    -- * Minimum length of 1
    microsoftEntraProviderRequestName :: Data.Text.Internal.Text,
    -- | property_mappings
    microsoftEntraProviderRequestPropertyMappings :: (GHC.Maybe.Maybe [Data.Text.Internal.Text]),
    -- | property_mappings_group: Property mappings used for group creation\/updating.
    microsoftEntraProviderRequestPropertyMappingsGroup :: (GHC.Maybe.Maybe [Data.Text.Internal.Text]),
    -- | tenant_id
    --
    -- Constraints:
    --
    -- * Minimum length of 1
    microsoftEntraProviderRequestTenantId :: Data.Text.Internal.Text,
    -- | user_delete_action
    microsoftEntraProviderRequestUserDeleteAction :: (GHC.Maybe.Maybe OutgoingSyncDeleteAction)
  }
  deriving
    ( GHC.Show.Show,
      GHC.Classes.Eq
    )

instance Data.Aeson.Types.ToJSON.ToJSON MicrosoftEntraProviderRequest where
  toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (["client_id" Data.Aeson.Types.ToJSON..= microsoftEntraProviderRequestClientId obj] : ["client_secret" Data.Aeson.Types.ToJSON..= microsoftEntraProviderRequestClientSecret obj] : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("dry_run" Data.Aeson.Types.ToJSON..=)) (microsoftEntraProviderRequestDryRun obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("exclude_users_service_account" Data.Aeson.Types.ToJSON..=)) (microsoftEntraProviderRequestExcludeUsersServiceAccount obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("filter_group" Data.Aeson.Types.ToJSON..=)) (microsoftEntraProviderRequestFilterGroup obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("group_delete_action" Data.Aeson.Types.ToJSON..=)) (microsoftEntraProviderRequestGroupDeleteAction obj) : ["name" Data.Aeson.Types.ToJSON..= microsoftEntraProviderRequestName obj] : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("property_mappings" Data.Aeson.Types.ToJSON..=)) (microsoftEntraProviderRequestPropertyMappings obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("property_mappings_group" Data.Aeson.Types.ToJSON..=)) (microsoftEntraProviderRequestPropertyMappingsGroup obj) : ["tenant_id" Data.Aeson.Types.ToJSON..= microsoftEntraProviderRequestTenantId obj] : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("user_delete_action" Data.Aeson.Types.ToJSON..=)) (microsoftEntraProviderRequestUserDeleteAction obj) : GHC.Base.mempty))
  toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (["client_id" Data.Aeson.Types.ToJSON..= microsoftEntraProviderRequestClientId obj] : ["client_secret" Data.Aeson.Types.ToJSON..= microsoftEntraProviderRequestClientSecret obj] : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("dry_run" Data.Aeson.Types.ToJSON..=)) (microsoftEntraProviderRequestDryRun obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("exclude_users_service_account" Data.Aeson.Types.ToJSON..=)) (microsoftEntraProviderRequestExcludeUsersServiceAccount obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("filter_group" Data.Aeson.Types.ToJSON..=)) (microsoftEntraProviderRequestFilterGroup obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("group_delete_action" Data.Aeson.Types.ToJSON..=)) (microsoftEntraProviderRequestGroupDeleteAction obj) : ["name" Data.Aeson.Types.ToJSON..= microsoftEntraProviderRequestName obj] : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("property_mappings" Data.Aeson.Types.ToJSON..=)) (microsoftEntraProviderRequestPropertyMappings obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("property_mappings_group" Data.Aeson.Types.ToJSON..=)) (microsoftEntraProviderRequestPropertyMappingsGroup obj) : ["tenant_id" Data.Aeson.Types.ToJSON..= microsoftEntraProviderRequestTenantId obj] : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("user_delete_action" Data.Aeson.Types.ToJSON..=)) (microsoftEntraProviderRequestUserDeleteAction obj) : GHC.Base.mempty)))

instance Data.Aeson.Types.FromJSON.FromJSON MicrosoftEntraProviderRequest where
  parseJSON = Data.Aeson.Types.FromJSON.withObject "MicrosoftEntraProviderRequest" (\obj -> ((((((((((GHC.Base.pure MicrosoftEntraProviderRequest GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "client_id")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "client_secret")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "dry_run")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "exclude_users_service_account")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "filter_group")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "group_delete_action")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "name")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "property_mappings")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "property_mappings_group")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "tenant_id")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "user_delete_action"))

-- | Create a new 'MicrosoftEntraProviderRequest' with all required fields.
mkMicrosoftEntraProviderRequest ::
  -- | 'microsoftEntraProviderRequestClientId'
  Data.Text.Internal.Text ->
  -- | 'microsoftEntraProviderRequestClientSecret'
  Data.Text.Internal.Text ->
  -- | 'microsoftEntraProviderRequestName'
  Data.Text.Internal.Text ->
  -- | 'microsoftEntraProviderRequestTenantId'
  Data.Text.Internal.Text ->
  MicrosoftEntraProviderRequest
mkMicrosoftEntraProviderRequest microsoftEntraProviderRequestClientId microsoftEntraProviderRequestClientSecret microsoftEntraProviderRequestName microsoftEntraProviderRequestTenantId =
  MicrosoftEntraProviderRequest
    { microsoftEntraProviderRequestClientId = microsoftEntraProviderRequestClientId,
      microsoftEntraProviderRequestClientSecret = microsoftEntraProviderRequestClientSecret,
      microsoftEntraProviderRequestDryRun = GHC.Maybe.Nothing,
      microsoftEntraProviderRequestExcludeUsersServiceAccount = GHC.Maybe.Nothing,
      microsoftEntraProviderRequestFilterGroup = GHC.Maybe.Nothing,
      microsoftEntraProviderRequestGroupDeleteAction = GHC.Maybe.Nothing,
      microsoftEntraProviderRequestName = microsoftEntraProviderRequestName,
      microsoftEntraProviderRequestPropertyMappings = GHC.Maybe.Nothing,
      microsoftEntraProviderRequestPropertyMappingsGroup = GHC.Maybe.Nothing,
      microsoftEntraProviderRequestTenantId = microsoftEntraProviderRequestTenantId,
      microsoftEntraProviderRequestUserDeleteAction = GHC.Maybe.Nothing
    }
