{-# LANGUAGE MultiWayIf #-}
-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.
{-# LANGUAGE OverloadedStrings #-}

-- | Contains the types generated from the schema MicrosoftEntraProviderGroupRequest
module AuthentikAPI.Types.MicrosoftEntraProviderGroupRequest where

import qualified AuthentikAPI.Common
import AuthentikAPI.TypeAlias
import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Functor
import qualified Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe

-- | Defines the object schema located at @components.schemas.MicrosoftEntraProviderGroupRequest@ in the specification.
--
-- MicrosoftEntraProviderGroup Serializer
data MicrosoftEntraProviderGroupRequest = MicrosoftEntraProviderGroupRequest
  { -- | group
    microsoftEntraProviderGroupRequestGroup :: Data.Text.Internal.Text,
    -- | microsoft_id
    --
    -- Constraints:
    --
    -- * Minimum length of 1
    microsoftEntraProviderGroupRequestMicrosoftId :: Data.Text.Internal.Text,
    -- | provider
    microsoftEntraProviderGroupRequestProvider :: GHC.Types.Int
  }
  deriving
    ( GHC.Show.Show,
      GHC.Classes.Eq
    )

instance Data.Aeson.Types.ToJSON.ToJSON MicrosoftEntraProviderGroupRequest where
  toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (["group" Data.Aeson.Types.ToJSON..= microsoftEntraProviderGroupRequestGroup obj] : ["microsoft_id" Data.Aeson.Types.ToJSON..= microsoftEntraProviderGroupRequestMicrosoftId obj] : ["provider" Data.Aeson.Types.ToJSON..= microsoftEntraProviderGroupRequestProvider obj] : GHC.Base.mempty))
  toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (["group" Data.Aeson.Types.ToJSON..= microsoftEntraProviderGroupRequestGroup obj] : ["microsoft_id" Data.Aeson.Types.ToJSON..= microsoftEntraProviderGroupRequestMicrosoftId obj] : ["provider" Data.Aeson.Types.ToJSON..= microsoftEntraProviderGroupRequestProvider obj] : GHC.Base.mempty)))

instance Data.Aeson.Types.FromJSON.FromJSON MicrosoftEntraProviderGroupRequest where
  parseJSON = Data.Aeson.Types.FromJSON.withObject "MicrosoftEntraProviderGroupRequest" (\obj -> ((GHC.Base.pure MicrosoftEntraProviderGroupRequest GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "group")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "microsoft_id")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "provider"))

-- | Create a new 'MicrosoftEntraProviderGroupRequest' with all required fields.
mkMicrosoftEntraProviderGroupRequest ::
  -- | 'microsoftEntraProviderGroupRequestGroup'
  Data.Text.Internal.Text ->
  -- | 'microsoftEntraProviderGroupRequestMicrosoftId'
  Data.Text.Internal.Text ->
  -- | 'microsoftEntraProviderGroupRequestProvider'
  GHC.Types.Int ->
  MicrosoftEntraProviderGroupRequest
mkMicrosoftEntraProviderGroupRequest microsoftEntraProviderGroupRequestGroup microsoftEntraProviderGroupRequestMicrosoftId microsoftEntraProviderGroupRequestProvider =
  MicrosoftEntraProviderGroupRequest
    { microsoftEntraProviderGroupRequestGroup = microsoftEntraProviderGroupRequestGroup,
      microsoftEntraProviderGroupRequestMicrosoftId = microsoftEntraProviderGroupRequestMicrosoftId,
      microsoftEntraProviderGroupRequestProvider = microsoftEntraProviderGroupRequestProvider
    }
