{-# LANGUAGE MultiWayIf #-}
-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.
{-# LANGUAGE OverloadedStrings #-}

-- | Contains the types generated from the schema ModelRequest
module AuthentikAPI.Types.ModelRequest where

import qualified AuthentikAPI.Common
import AuthentikAPI.TypeAlias
import {-# SOURCE #-} AuthentikAPI.Types.GoogleWorkspaceProviderRequest
import {-# SOURCE #-} AuthentikAPI.Types.LDAPProviderRequest
import {-# SOURCE #-} AuthentikAPI.Types.MicrosoftEntraProviderRequest
import {-# SOURCE #-} AuthentikAPI.Types.OAuth2ProviderRequest
import {-# SOURCE #-} AuthentikAPI.Types.ProxyProviderRequest
import {-# SOURCE #-} AuthentikAPI.Types.RACProviderRequest
import {-# SOURCE #-} AuthentikAPI.Types.RadiusProviderRequest
import {-# SOURCE #-} AuthentikAPI.Types.SAMLProviderRequest
import {-# SOURCE #-} AuthentikAPI.Types.SCIMProviderRequest
import {-# SOURCE #-} AuthentikAPI.Types.SSFProviderRequest
import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Functor
import qualified Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe

-- | Defines the oneOf schema located at @components.schemas.modelRequest.oneOf@ in the specification.
data ModelRequestVariants
  = ModelRequestGoogleWorkspaceProviderRequest GoogleWorkspaceProviderRequest
  | ModelRequestLDAPProviderRequest LDAPProviderRequest
  | ModelRequestMicrosoftEntraProviderRequest MicrosoftEntraProviderRequest
  | ModelRequestOAuth2ProviderRequest OAuth2ProviderRequest
  | ModelRequestProxyProviderRequest ProxyProviderRequest
  | ModelRequestRACProviderRequest RACProviderRequest
  | ModelRequestRadiusProviderRequest RadiusProviderRequest
  | ModelRequestSAMLProviderRequest SAMLProviderRequest
  | ModelRequestSCIMProviderRequest SCIMProviderRequest
  | ModelRequestSSFProviderRequest SSFProviderRequest
  deriving (GHC.Show.Show, GHC.Classes.Eq)

instance Data.Aeson.Types.ToJSON.ToJSON ModelRequestVariants where
  toJSON (ModelRequestGoogleWorkspaceProviderRequest a) = Data.Aeson.Types.ToJSON.toJSON a
  toJSON (ModelRequestLDAPProviderRequest a) = Data.Aeson.Types.ToJSON.toJSON a
  toJSON (ModelRequestMicrosoftEntraProviderRequest a) = Data.Aeson.Types.ToJSON.toJSON a
  toJSON (ModelRequestOAuth2ProviderRequest a) = Data.Aeson.Types.ToJSON.toJSON a
  toJSON (ModelRequestProxyProviderRequest a) = Data.Aeson.Types.ToJSON.toJSON a
  toJSON (ModelRequestRACProviderRequest a) = Data.Aeson.Types.ToJSON.toJSON a
  toJSON (ModelRequestRadiusProviderRequest a) = Data.Aeson.Types.ToJSON.toJSON a
  toJSON (ModelRequestSAMLProviderRequest a) = Data.Aeson.Types.ToJSON.toJSON a
  toJSON (ModelRequestSCIMProviderRequest a) = Data.Aeson.Types.ToJSON.toJSON a
  toJSON (ModelRequestSSFProviderRequest a) = Data.Aeson.Types.ToJSON.toJSON a

instance Data.Aeson.Types.FromJSON.FromJSON ModelRequestVariants where
  parseJSON val = case (ModelRequestGoogleWorkspaceProviderRequest Data.Functor.<$> Data.Aeson.Types.FromJSON.fromJSON val) GHC.Base.<|> ((ModelRequestLDAPProviderRequest Data.Functor.<$> Data.Aeson.Types.FromJSON.fromJSON val) GHC.Base.<|> ((ModelRequestMicrosoftEntraProviderRequest Data.Functor.<$> Data.Aeson.Types.FromJSON.fromJSON val) GHC.Base.<|> ((ModelRequestOAuth2ProviderRequest Data.Functor.<$> Data.Aeson.Types.FromJSON.fromJSON val) GHC.Base.<|> ((ModelRequestProxyProviderRequest Data.Functor.<$> Data.Aeson.Types.FromJSON.fromJSON val) GHC.Base.<|> ((ModelRequestRACProviderRequest Data.Functor.<$> Data.Aeson.Types.FromJSON.fromJSON val) GHC.Base.<|> ((ModelRequestRadiusProviderRequest Data.Functor.<$> Data.Aeson.Types.FromJSON.fromJSON val) GHC.Base.<|> ((ModelRequestSAMLProviderRequest Data.Functor.<$> Data.Aeson.Types.FromJSON.fromJSON val) GHC.Base.<|> ((ModelRequestSCIMProviderRequest Data.Functor.<$> Data.Aeson.Types.FromJSON.fromJSON val) GHC.Base.<|> ((ModelRequestSSFProviderRequest Data.Functor.<$> Data.Aeson.Types.FromJSON.fromJSON val) GHC.Base.<|> Data.Aeson.Types.Internal.Error "No variant matched"))))))))) of
    Data.Aeson.Types.Internal.Success a -> GHC.Base.pure a
    Data.Aeson.Types.Internal.Error a -> Control.Monad.Fail.fail a

-- | Defines an alias for the schema located at @components.schemas.modelRequest.oneOf@ in the specification.
type ModelRequest = ModelRequestVariants
