module AuthentikAPI.Types.NotificationTransportModeEnum where
import qualified Data.Aeson
import qualified AuthentikAPI.Common
data NotificationTransportModeEnum
instance Show NotificationTransportModeEnum
instance Eq NotificationTransportModeEnum
instance Data.Aeson.FromJSON NotificationTransportModeEnum
instance Data.Aeson.ToJSON NotificationTransportModeEnum
