module AuthentikAPI.Types.OAuthDeviceCodeFinishChallengeResponseRequest where
import qualified Data.Aeson
import qualified AuthentikAPI.Common
data OAuthDeviceCodeFinishChallengeResponseRequest
instance Show OAuthDeviceCodeFinishChallengeResponseRequest
instance Eq OAuthDeviceCodeFinishChallengeResponseRequest
instance Data.Aeson.FromJSON OAuthDeviceCodeFinishChallengeResponseRequest
instance Data.Aeson.ToJSON OAuthDeviceCodeFinishChallengeResponseRequest
