{-# LANGUAGE MultiWayIf #-}
-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.
{-# LANGUAGE OverloadedStrings #-}

-- | Contains the types generated from the schema PaginatedPasswordPolicyList
module AuthentikAPI.Types.PaginatedPasswordPolicyList where

import qualified AuthentikAPI.Common
import AuthentikAPI.TypeAlias
import {-# SOURCE #-} AuthentikAPI.Types.Pagination
import {-# SOURCE #-} AuthentikAPI.Types.PasswordPolicy
import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Functor
import qualified Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe

-- | Defines the object schema located at @components.schemas.PaginatedPasswordPolicyList@ in the specification.
data PaginatedPasswordPolicyList = PaginatedPasswordPolicyList
  { -- | pagination
    paginatedPasswordPolicyListPagination :: Pagination,
    -- | results
    paginatedPasswordPolicyListResults :: [PasswordPolicy]
  }
  deriving
    ( GHC.Show.Show,
      GHC.Classes.Eq
    )

instance Data.Aeson.Types.ToJSON.ToJSON PaginatedPasswordPolicyList where
  toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (["pagination" Data.Aeson.Types.ToJSON..= paginatedPasswordPolicyListPagination obj] : ["results" Data.Aeson.Types.ToJSON..= paginatedPasswordPolicyListResults obj] : GHC.Base.mempty))
  toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (["pagination" Data.Aeson.Types.ToJSON..= paginatedPasswordPolicyListPagination obj] : ["results" Data.Aeson.Types.ToJSON..= paginatedPasswordPolicyListResults obj] : GHC.Base.mempty)))

instance Data.Aeson.Types.FromJSON.FromJSON PaginatedPasswordPolicyList where
  parseJSON = Data.Aeson.Types.FromJSON.withObject "PaginatedPasswordPolicyList" (\obj -> (GHC.Base.pure PaginatedPasswordPolicyList GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "pagination")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "results"))

-- | Create a new 'PaginatedPasswordPolicyList' with all required fields.
mkPaginatedPasswordPolicyList ::
  -- | 'paginatedPasswordPolicyListPagination'
  Pagination ->
  -- | 'paginatedPasswordPolicyListResults'
  [PasswordPolicy] ->
  PaginatedPasswordPolicyList
mkPaginatedPasswordPolicyList paginatedPasswordPolicyListPagination paginatedPasswordPolicyListResults =
  PaginatedPasswordPolicyList
    { paginatedPasswordPolicyListPagination = paginatedPasswordPolicyListPagination,
      paginatedPasswordPolicyListResults = paginatedPasswordPolicyListResults
    }
