module AuthentikAPI.Types.PaginatedProxyOutpostConfigList where
import qualified Data.Aeson
import qualified AuthentikAPI.Common
data PaginatedProxyOutpostConfigList
instance Show PaginatedProxyOutpostConfigList
instance Eq PaginatedProxyOutpostConfigList
instance Data.Aeson.FromJSON PaginatedProxyOutpostConfigList
instance Data.Aeson.ToJSON PaginatedProxyOutpostConfigList
