{-# LANGUAGE MultiWayIf #-}
-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.
{-# LANGUAGE OverloadedStrings #-}

-- | Contains the types generated from the schema PaginatedSourceStageList
module AuthentikAPI.Types.PaginatedSourceStageList where

import qualified AuthentikAPI.Common
import AuthentikAPI.TypeAlias
import {-# SOURCE #-} AuthentikAPI.Types.Pagination
import {-# SOURCE #-} AuthentikAPI.Types.SourceStage
import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Functor
import qualified Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe

-- | Defines the object schema located at @components.schemas.PaginatedSourceStageList@ in the specification.
data PaginatedSourceStageList = PaginatedSourceStageList
  { -- | pagination
    paginatedSourceStageListPagination :: Pagination,
    -- | results
    paginatedSourceStageListResults :: [SourceStage]
  }
  deriving
    ( GHC.Show.Show,
      GHC.Classes.Eq
    )

instance Data.Aeson.Types.ToJSON.ToJSON PaginatedSourceStageList where
  toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (["pagination" Data.Aeson.Types.ToJSON..= paginatedSourceStageListPagination obj] : ["results" Data.Aeson.Types.ToJSON..= paginatedSourceStageListResults obj] : GHC.Base.mempty))
  toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (["pagination" Data.Aeson.Types.ToJSON..= paginatedSourceStageListPagination obj] : ["results" Data.Aeson.Types.ToJSON..= paginatedSourceStageListResults obj] : GHC.Base.mempty)))

instance Data.Aeson.Types.FromJSON.FromJSON PaginatedSourceStageList where
  parseJSON = Data.Aeson.Types.FromJSON.withObject "PaginatedSourceStageList" (\obj -> (GHC.Base.pure PaginatedSourceStageList GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "pagination")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "results"))

-- | Create a new 'PaginatedSourceStageList' with all required fields.
mkPaginatedSourceStageList ::
  -- | 'paginatedSourceStageListPagination'
  Pagination ->
  -- | 'paginatedSourceStageListResults'
  [SourceStage] ->
  PaginatedSourceStageList
mkPaginatedSourceStageList paginatedSourceStageListPagination paginatedSourceStageListResults =
  PaginatedSourceStageList
    { paginatedSourceStageListPagination = paginatedSourceStageListPagination,
      paginatedSourceStageListResults = paginatedSourceStageListResults
    }
