module AuthentikAPI.Types.PaginatedKerberosSourcePropertyMappingList where
import qualified Data.Aeson
import qualified AuthentikAPI.Common
data PaginatedKerberosSourcePropertyMappingList
instance Show PaginatedKerberosSourcePropertyMappingList
instance Eq PaginatedKerberosSourcePropertyMappingList
instance Data.Aeson.FromJSON PaginatedKerberosSourcePropertyMappingList
instance Data.Aeson.ToJSON PaginatedKerberosSourcePropertyMappingList
