module AuthentikAPI.Types.PaginatedGroupSAMLSourceConnectionList where
import qualified Data.Aeson
import qualified AuthentikAPI.Common
data PaginatedGroupSAMLSourceConnectionList
instance Show PaginatedGroupSAMLSourceConnectionList
instance Eq PaginatedGroupSAMLSourceConnectionList
instance Data.Aeson.FromJSON PaginatedGroupSAMLSourceConnectionList
instance Data.Aeson.ToJSON PaginatedGroupSAMLSourceConnectionList
