{-# LANGUAGE MultiWayIf #-}
-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.
{-# LANGUAGE OverloadedStrings #-}

-- | Contains the types generated from the schema Pagination
module AuthentikAPI.Types.Pagination where

import qualified AuthentikAPI.Common
import AuthentikAPI.TypeAlias
import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Functor
import qualified Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe

-- | Defines the object schema located at @components.schemas.Pagination@ in the specification.
data Pagination = Pagination
  { -- | count
    paginationCount :: GHC.Types.Double,
    -- | current
    paginationCurrent :: GHC.Types.Double,
    -- | end_index
    paginationEndIndex :: GHC.Types.Double,
    -- | next
    paginationNext :: GHC.Types.Double,
    -- | previous
    paginationPrevious :: GHC.Types.Double,
    -- | start_index
    paginationStartIndex :: GHC.Types.Double,
    -- | total_pages
    paginationTotalPages :: GHC.Types.Double
  }
  deriving
    ( GHC.Show.Show,
      GHC.Classes.Eq
    )

instance Data.Aeson.Types.ToJSON.ToJSON Pagination where
  toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (["count" Data.Aeson.Types.ToJSON..= paginationCount obj] : ["current" Data.Aeson.Types.ToJSON..= paginationCurrent obj] : ["end_index" Data.Aeson.Types.ToJSON..= paginationEndIndex obj] : ["next" Data.Aeson.Types.ToJSON..= paginationNext obj] : ["previous" Data.Aeson.Types.ToJSON..= paginationPrevious obj] : ["start_index" Data.Aeson.Types.ToJSON..= paginationStartIndex obj] : ["total_pages" Data.Aeson.Types.ToJSON..= paginationTotalPages obj] : GHC.Base.mempty))
  toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (["count" Data.Aeson.Types.ToJSON..= paginationCount obj] : ["current" Data.Aeson.Types.ToJSON..= paginationCurrent obj] : ["end_index" Data.Aeson.Types.ToJSON..= paginationEndIndex obj] : ["next" Data.Aeson.Types.ToJSON..= paginationNext obj] : ["previous" Data.Aeson.Types.ToJSON..= paginationPrevious obj] : ["start_index" Data.Aeson.Types.ToJSON..= paginationStartIndex obj] : ["total_pages" Data.Aeson.Types.ToJSON..= paginationTotalPages obj] : GHC.Base.mempty)))

instance Data.Aeson.Types.FromJSON.FromJSON Pagination where
  parseJSON = Data.Aeson.Types.FromJSON.withObject "Pagination" (\obj -> ((((((GHC.Base.pure Pagination GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "count")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "current")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "end_index")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "next")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "previous")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "start_index")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "total_pages"))

-- | Create a new 'Pagination' with all required fields.
mkPagination ::
  -- | 'paginationCount'
  GHC.Types.Double ->
  -- | 'paginationCurrent'
  GHC.Types.Double ->
  -- | 'paginationEndIndex'
  GHC.Types.Double ->
  -- | 'paginationNext'
  GHC.Types.Double ->
  -- | 'paginationPrevious'
  GHC.Types.Double ->
  -- | 'paginationStartIndex'
  GHC.Types.Double ->
  -- | 'paginationTotalPages'
  GHC.Types.Double ->
  Pagination
mkPagination paginationCount paginationCurrent paginationEndIndex paginationNext paginationPrevious paginationStartIndex paginationTotalPages =
  Pagination
    { paginationCount = paginationCount,
      paginationCurrent = paginationCurrent,
      paginationEndIndex = paginationEndIndex,
      paginationNext = paginationNext,
      paginationPrevious = paginationPrevious,
      paginationStartIndex = paginationStartIndex,
      paginationTotalPages = paginationTotalPages
    }
