module AuthentikAPI.Types.PatchedSCIMSourceGroupRequest where
import qualified Data.Aeson
import qualified AuthentikAPI.Common
data PatchedSCIMSourceGroupRequest
instance Show PatchedSCIMSourceGroupRequest
instance Eq PatchedSCIMSourceGroupRequest
instance Data.Aeson.FromJSON PatchedSCIMSourceGroupRequest
instance Data.Aeson.ToJSON PatchedSCIMSourceGroupRequest
