module AuthentikAPI.Types.PatchedInvitationStageRequest where
import qualified Data.Aeson
import qualified AuthentikAPI.Common
data PatchedInvitationStageRequest
instance Show PatchedInvitationStageRequest
instance Eq PatchedInvitationStageRequest
instance Data.Aeson.FromJSON PatchedInvitationStageRequest
instance Data.Aeson.ToJSON PatchedInvitationStageRequest
