module AuthentikAPI.Types.PatchedNotificationWebhookMappingRequest where
import qualified Data.Aeson
import qualified AuthentikAPI.Common
data PatchedNotificationWebhookMappingRequest
instance Show PatchedNotificationWebhookMappingRequest
instance Eq PatchedNotificationWebhookMappingRequest
instance Data.Aeson.FromJSON PatchedNotificationWebhookMappingRequest
instance Data.Aeson.ToJSON PatchedNotificationWebhookMappingRequest
