module AuthentikAPI.Types.PatchedReputationPolicyRequest where
import qualified Data.Aeson
import qualified AuthentikAPI.Common
data PatchedReputationPolicyRequest
instance Show PatchedReputationPolicyRequest
instance Eq PatchedReputationPolicyRequest
instance Data.Aeson.FromJSON PatchedReputationPolicyRequest
instance Data.Aeson.ToJSON PatchedReputationPolicyRequest
