{-# LANGUAGE MultiWayIf #-}
-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.
{-# LANGUAGE OverloadedStrings #-}

-- | Contains the types generated from the schema PatchedUserSourceConnectionRequest
module AuthentikAPI.Types.PatchedUserSourceConnectionRequest where

import qualified AuthentikAPI.Common
import AuthentikAPI.TypeAlias
import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Functor
import qualified Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe

-- | Defines the object schema located at @components.schemas.PatchedUserSourceConnectionRequest@ in the specification.
--
-- User source connection
data PatchedUserSourceConnectionRequest = PatchedUserSourceConnectionRequest
  { -- | identifier
    --
    -- Constraints:
    --
    -- * Minimum length of 1
    patchedUserSourceConnectionRequestIdentifier :: (GHC.Maybe.Maybe Data.Text.Internal.Text),
    -- | source
    patchedUserSourceConnectionRequestSource :: (GHC.Maybe.Maybe Data.Text.Internal.Text),
    -- | user
    patchedUserSourceConnectionRequestUser :: (GHC.Maybe.Maybe GHC.Types.Int)
  }
  deriving
    ( GHC.Show.Show,
      GHC.Classes.Eq
    )

instance Data.Aeson.Types.ToJSON.ToJSON PatchedUserSourceConnectionRequest where
  toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("identifier" Data.Aeson.Types.ToJSON..=)) (patchedUserSourceConnectionRequestIdentifier obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("source" Data.Aeson.Types.ToJSON..=)) (patchedUserSourceConnectionRequestSource obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("user" Data.Aeson.Types.ToJSON..=)) (patchedUserSourceConnectionRequestUser obj) : GHC.Base.mempty))
  toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("identifier" Data.Aeson.Types.ToJSON..=)) (patchedUserSourceConnectionRequestIdentifier obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("source" Data.Aeson.Types.ToJSON..=)) (patchedUserSourceConnectionRequestSource obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("user" Data.Aeson.Types.ToJSON..=)) (patchedUserSourceConnectionRequestUser obj) : GHC.Base.mempty)))

instance Data.Aeson.Types.FromJSON.FromJSON PatchedUserSourceConnectionRequest where
  parseJSON = Data.Aeson.Types.FromJSON.withObject "PatchedUserSourceConnectionRequest" (\obj -> ((GHC.Base.pure PatchedUserSourceConnectionRequest GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "identifier")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "source")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "user"))

-- | Create a new 'PatchedUserSourceConnectionRequest' with all required fields.
mkPatchedUserSourceConnectionRequest :: PatchedUserSourceConnectionRequest
mkPatchedUserSourceConnectionRequest =
  PatchedUserSourceConnectionRequest
    { patchedUserSourceConnectionRequestIdentifier = GHC.Maybe.Nothing,
      patchedUserSourceConnectionRequestSource = GHC.Maybe.Nothing,
      patchedUserSourceConnectionRequestUser = GHC.Maybe.Nothing
    }
