{-# LANGUAGE MultiWayIf #-}
-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.
{-# LANGUAGE OverloadedStrings #-}

-- | Contains the types generated from the schema PatchedCertificateKeyPairRequest
module AuthentikAPI.Types.PatchedCertificateKeyPairRequest where

import qualified AuthentikAPI.Common
import AuthentikAPI.TypeAlias
import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Functor
import qualified Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe

-- | Defines the object schema located at @components.schemas.PatchedCertificateKeyPairRequest@ in the specification.
--
-- CertificateKeyPair Serializer
data PatchedCertificateKeyPairRequest = PatchedCertificateKeyPairRequest
  { -- | certificate_data: PEM-encoded Certificate data
    --
    -- Constraints:
    --
    -- * Minimum length of 1
    patchedCertificateKeyPairRequestCertificateData :: (GHC.Maybe.Maybe Data.Text.Internal.Text),
    -- | key_data: Optional Private Key. If this is set, you can use this keypair for encryption.
    patchedCertificateKeyPairRequestKeyData :: (GHC.Maybe.Maybe Data.Text.Internal.Text),
    -- | name
    --
    -- Constraints:
    --
    -- * Minimum length of 1
    patchedCertificateKeyPairRequestName :: (GHC.Maybe.Maybe Data.Text.Internal.Text)
  }
  deriving
    ( GHC.Show.Show,
      GHC.Classes.Eq
    )

instance Data.Aeson.Types.ToJSON.ToJSON PatchedCertificateKeyPairRequest where
  toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("certificate_data" Data.Aeson.Types.ToJSON..=)) (patchedCertificateKeyPairRequestCertificateData obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("key_data" Data.Aeson.Types.ToJSON..=)) (patchedCertificateKeyPairRequestKeyData obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("name" Data.Aeson.Types.ToJSON..=)) (patchedCertificateKeyPairRequestName obj) : GHC.Base.mempty))
  toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("certificate_data" Data.Aeson.Types.ToJSON..=)) (patchedCertificateKeyPairRequestCertificateData obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("key_data" Data.Aeson.Types.ToJSON..=)) (patchedCertificateKeyPairRequestKeyData obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("name" Data.Aeson.Types.ToJSON..=)) (patchedCertificateKeyPairRequestName obj) : GHC.Base.mempty)))

instance Data.Aeson.Types.FromJSON.FromJSON PatchedCertificateKeyPairRequest where
  parseJSON = Data.Aeson.Types.FromJSON.withObject "PatchedCertificateKeyPairRequest" (\obj -> ((GHC.Base.pure PatchedCertificateKeyPairRequest GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "certificate_data")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "key_data")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "name"))

-- | Create a new 'PatchedCertificateKeyPairRequest' with all required fields.
mkPatchedCertificateKeyPairRequest :: PatchedCertificateKeyPairRequest
mkPatchedCertificateKeyPairRequest =
  PatchedCertificateKeyPairRequest
    { patchedCertificateKeyPairRequestCertificateData = GHC.Maybe.Nothing,
      patchedCertificateKeyPairRequestKeyData = GHC.Maybe.Nothing,
      patchedCertificateKeyPairRequestName = GHC.Maybe.Nothing
    }
