module AuthentikAPI.Types.PatchedLDAPSourcePropertyMappingRequest where
import qualified Data.Aeson
import qualified AuthentikAPI.Common
data PatchedLDAPSourcePropertyMappingRequest
instance Show PatchedLDAPSourcePropertyMappingRequest
instance Eq PatchedLDAPSourcePropertyMappingRequest
instance Data.Aeson.FromJSON PatchedLDAPSourcePropertyMappingRequest
instance Data.Aeson.ToJSON PatchedLDAPSourcePropertyMappingRequest
