{-# LANGUAGE MultiWayIf #-}
-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.
{-# LANGUAGE OverloadedStrings #-}

-- | Contains the types generated from the schema PatchedGeoIPPolicyRequest
module AuthentikAPI.Types.PatchedGeoIPPolicyRequest where

import qualified AuthentikAPI.Common
import AuthentikAPI.TypeAlias
import {-# SOURCE #-} AuthentikAPI.Types.CountryCodeEnum
import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Functor
import qualified Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe

-- | Defines the object schema located at @components.schemas.PatchedGeoIPPolicyRequest@ in the specification.
--
-- GeoIP Policy Serializer
data PatchedGeoIPPolicyRequest = PatchedGeoIPPolicyRequest
  { -- | asns
    patchedGeoIPPolicyRequestAsns :: (GHC.Maybe.Maybe [GHC.Types.Int]),
    -- | check_history_distance
    patchedGeoIPPolicyRequestCheckHistoryDistance :: (GHC.Maybe.Maybe GHC.Types.Bool),
    -- | check_impossible_travel
    patchedGeoIPPolicyRequestCheckImpossibleTravel :: (GHC.Maybe.Maybe GHC.Types.Bool),
    -- | countries
    --
    -- Constraints:
    --
    -- * Must have a maximum of 249 items
    patchedGeoIPPolicyRequestCountries :: (GHC.Maybe.Maybe [CountryCodeEnum]),
    -- | distance_tolerance_km
    --
    -- Constraints:
    --
    -- * Maxium  of 2.1474836e9
    -- * Minimum  of 0.0
    patchedGeoIPPolicyRequestDistanceToleranceKm :: (GHC.Maybe.Maybe GHC.Types.Int),
    -- | execution_logging: When this option is enabled, all executions of this policy will be logged. By default, only execution errors are logged.
    patchedGeoIPPolicyRequestExecutionLogging :: (GHC.Maybe.Maybe GHC.Types.Bool),
    -- | history_login_count
    --
    -- Constraints:
    --
    -- * Maxium  of 2.1474836e9
    -- * Minimum  of 0.0
    patchedGeoIPPolicyRequestHistoryLoginCount :: (GHC.Maybe.Maybe GHC.Types.Int),
    -- | history_max_distance_km
    --
    -- Constraints:
    --
    -- * Maxium  of 9.223372e18
    -- * Minimum  of 0.0
    patchedGeoIPPolicyRequestHistoryMaxDistanceKm :: (GHC.Maybe.Maybe GHC.Int.Int64),
    -- | impossible_tolerance_km
    --
    -- Constraints:
    --
    -- * Maxium  of 2.1474836e9
    -- * Minimum  of 0.0
    patchedGeoIPPolicyRequestImpossibleToleranceKm :: (GHC.Maybe.Maybe GHC.Types.Int),
    -- | name
    --
    -- Constraints:
    --
    -- * Minimum length of 1
    patchedGeoIPPolicyRequestName :: (GHC.Maybe.Maybe Data.Text.Internal.Text)
  }
  deriving
    ( GHC.Show.Show,
      GHC.Classes.Eq
    )

instance Data.Aeson.Types.ToJSON.ToJSON PatchedGeoIPPolicyRequest where
  toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("asns" Data.Aeson.Types.ToJSON..=)) (patchedGeoIPPolicyRequestAsns obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("check_history_distance" Data.Aeson.Types.ToJSON..=)) (patchedGeoIPPolicyRequestCheckHistoryDistance obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("check_impossible_travel" Data.Aeson.Types.ToJSON..=)) (patchedGeoIPPolicyRequestCheckImpossibleTravel obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("countries" Data.Aeson.Types.ToJSON..=)) (patchedGeoIPPolicyRequestCountries obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("distance_tolerance_km" Data.Aeson.Types.ToJSON..=)) (patchedGeoIPPolicyRequestDistanceToleranceKm obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("execution_logging" Data.Aeson.Types.ToJSON..=)) (patchedGeoIPPolicyRequestExecutionLogging obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("history_login_count" Data.Aeson.Types.ToJSON..=)) (patchedGeoIPPolicyRequestHistoryLoginCount obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("history_max_distance_km" Data.Aeson.Types.ToJSON..=)) (patchedGeoIPPolicyRequestHistoryMaxDistanceKm obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("impossible_tolerance_km" Data.Aeson.Types.ToJSON..=)) (patchedGeoIPPolicyRequestImpossibleToleranceKm obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("name" Data.Aeson.Types.ToJSON..=)) (patchedGeoIPPolicyRequestName obj) : GHC.Base.mempty))
  toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("asns" Data.Aeson.Types.ToJSON..=)) (patchedGeoIPPolicyRequestAsns obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("check_history_distance" Data.Aeson.Types.ToJSON..=)) (patchedGeoIPPolicyRequestCheckHistoryDistance obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("check_impossible_travel" Data.Aeson.Types.ToJSON..=)) (patchedGeoIPPolicyRequestCheckImpossibleTravel obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("countries" Data.Aeson.Types.ToJSON..=)) (patchedGeoIPPolicyRequestCountries obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("distance_tolerance_km" Data.Aeson.Types.ToJSON..=)) (patchedGeoIPPolicyRequestDistanceToleranceKm obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("execution_logging" Data.Aeson.Types.ToJSON..=)) (patchedGeoIPPolicyRequestExecutionLogging obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("history_login_count" Data.Aeson.Types.ToJSON..=)) (patchedGeoIPPolicyRequestHistoryLoginCount obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("history_max_distance_km" Data.Aeson.Types.ToJSON..=)) (patchedGeoIPPolicyRequestHistoryMaxDistanceKm obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("impossible_tolerance_km" Data.Aeson.Types.ToJSON..=)) (patchedGeoIPPolicyRequestImpossibleToleranceKm obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("name" Data.Aeson.Types.ToJSON..=)) (patchedGeoIPPolicyRequestName obj) : GHC.Base.mempty)))

instance Data.Aeson.Types.FromJSON.FromJSON PatchedGeoIPPolicyRequest where
  parseJSON = Data.Aeson.Types.FromJSON.withObject "PatchedGeoIPPolicyRequest" (\obj -> (((((((((GHC.Base.pure PatchedGeoIPPolicyRequest GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "asns")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "check_history_distance")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "check_impossible_travel")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "countries")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "distance_tolerance_km")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "execution_logging")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "history_login_count")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "history_max_distance_km")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "impossible_tolerance_km")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "name"))

-- | Create a new 'PatchedGeoIPPolicyRequest' with all required fields.
mkPatchedGeoIPPolicyRequest :: PatchedGeoIPPolicyRequest
mkPatchedGeoIPPolicyRequest =
  PatchedGeoIPPolicyRequest
    { patchedGeoIPPolicyRequestAsns = GHC.Maybe.Nothing,
      patchedGeoIPPolicyRequestCheckHistoryDistance = GHC.Maybe.Nothing,
      patchedGeoIPPolicyRequestCheckImpossibleTravel = GHC.Maybe.Nothing,
      patchedGeoIPPolicyRequestCountries = GHC.Maybe.Nothing,
      patchedGeoIPPolicyRequestDistanceToleranceKm = GHC.Maybe.Nothing,
      patchedGeoIPPolicyRequestExecutionLogging = GHC.Maybe.Nothing,
      patchedGeoIPPolicyRequestHistoryLoginCount = GHC.Maybe.Nothing,
      patchedGeoIPPolicyRequestHistoryMaxDistanceKm = GHC.Maybe.Nothing,
      patchedGeoIPPolicyRequestImpossibleToleranceKm = GHC.Maybe.Nothing,
      patchedGeoIPPolicyRequestName = GHC.Maybe.Nothing
    }
