module AuthentikAPI.Types.PatchedAuthenticatorTOTPStageRequest where
import qualified Data.Aeson
import qualified AuthentikAPI.Common
data PatchedAuthenticatorTOTPStageRequest
instance Show PatchedAuthenticatorTOTPStageRequest
instance Eq PatchedAuthenticatorTOTPStageRequest
instance Data.Aeson.FromJSON PatchedAuthenticatorTOTPStageRequest
instance Data.Aeson.ToJSON PatchedAuthenticatorTOTPStageRequest
