module AuthentikAPI.Types.PatchedSAMLSourcePropertyMappingRequest where
import qualified Data.Aeson
import qualified AuthentikAPI.Common
data PatchedSAMLSourcePropertyMappingRequest
instance Show PatchedSAMLSourcePropertyMappingRequest
instance Eq PatchedSAMLSourcePropertyMappingRequest
instance Data.Aeson.FromJSON PatchedSAMLSourcePropertyMappingRequest
instance Data.Aeson.ToJSON PatchedSAMLSourcePropertyMappingRequest
