{-# LANGUAGE MultiWayIf #-}
-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.
{-# LANGUAGE OverloadedStrings #-}

-- | Contains the types generated from the schema PatchedAuthenticatorStaticStageRequest
module AuthentikAPI.Types.PatchedAuthenticatorStaticStageRequest where

import qualified AuthentikAPI.Common
import AuthentikAPI.TypeAlias
import {-# SOURCE #-} AuthentikAPI.Types.FlowSetRequest
import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Functor
import qualified Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe

-- | Defines the object schema located at @components.schemas.PatchedAuthenticatorStaticStageRequest@ in the specification.
--
-- AuthenticatorStaticStage Serializer
data PatchedAuthenticatorStaticStageRequest = PatchedAuthenticatorStaticStageRequest
  { -- | configure_flow: Flow used by an authenticated user to configure this Stage. If empty, user will not be able to configure this stage.
    patchedAuthenticatorStaticStageRequestConfigureFlow :: (GHC.Maybe.Maybe (AuthentikAPI.Common.Nullable Data.Text.Internal.Text)),
    -- | flow_set
    patchedAuthenticatorStaticStageRequestFlowSet :: (GHC.Maybe.Maybe [FlowSetRequest]),
    -- | friendly_name
    --
    -- Constraints:
    --
    -- * Minimum length of 1
    patchedAuthenticatorStaticStageRequestFriendlyName :: (GHC.Maybe.Maybe (AuthentikAPI.Common.Nullable Data.Text.Internal.Text)),
    -- | name
    --
    -- Constraints:
    --
    -- * Minimum length of 1
    patchedAuthenticatorStaticStageRequestName :: (GHC.Maybe.Maybe Data.Text.Internal.Text),
    -- | token_count
    --
    -- Constraints:
    --
    -- * Maxium  of 2.1474836e9
    -- * Minimum  of 0.0
    patchedAuthenticatorStaticStageRequestTokenCount :: (GHC.Maybe.Maybe GHC.Types.Int),
    -- | token_length
    --
    -- Constraints:
    --
    -- * Maxium  of 2.1474836e9
    -- * Minimum  of 0.0
    patchedAuthenticatorStaticStageRequestTokenLength :: (GHC.Maybe.Maybe GHC.Types.Int)
  }
  deriving
    ( GHC.Show.Show,
      GHC.Classes.Eq
    )

instance Data.Aeson.Types.ToJSON.ToJSON PatchedAuthenticatorStaticStageRequest where
  toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("configure_flow" Data.Aeson.Types.ToJSON..=)) (patchedAuthenticatorStaticStageRequestConfigureFlow obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("flow_set" Data.Aeson.Types.ToJSON..=)) (patchedAuthenticatorStaticStageRequestFlowSet obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("friendly_name" Data.Aeson.Types.ToJSON..=)) (patchedAuthenticatorStaticStageRequestFriendlyName obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("name" Data.Aeson.Types.ToJSON..=)) (patchedAuthenticatorStaticStageRequestName obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("token_count" Data.Aeson.Types.ToJSON..=)) (patchedAuthenticatorStaticStageRequestTokenCount obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("token_length" Data.Aeson.Types.ToJSON..=)) (patchedAuthenticatorStaticStageRequestTokenLength obj) : GHC.Base.mempty))
  toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("configure_flow" Data.Aeson.Types.ToJSON..=)) (patchedAuthenticatorStaticStageRequestConfigureFlow obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("flow_set" Data.Aeson.Types.ToJSON..=)) (patchedAuthenticatorStaticStageRequestFlowSet obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("friendly_name" Data.Aeson.Types.ToJSON..=)) (patchedAuthenticatorStaticStageRequestFriendlyName obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("name" Data.Aeson.Types.ToJSON..=)) (patchedAuthenticatorStaticStageRequestName obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("token_count" Data.Aeson.Types.ToJSON..=)) (patchedAuthenticatorStaticStageRequestTokenCount obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("token_length" Data.Aeson.Types.ToJSON..=)) (patchedAuthenticatorStaticStageRequestTokenLength obj) : GHC.Base.mempty)))

instance Data.Aeson.Types.FromJSON.FromJSON PatchedAuthenticatorStaticStageRequest where
  parseJSON = Data.Aeson.Types.FromJSON.withObject "PatchedAuthenticatorStaticStageRequest" (\obj -> (((((GHC.Base.pure PatchedAuthenticatorStaticStageRequest GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "configure_flow")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "flow_set")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "friendly_name")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "name")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "token_count")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "token_length"))

-- | Create a new 'PatchedAuthenticatorStaticStageRequest' with all required fields.
mkPatchedAuthenticatorStaticStageRequest :: PatchedAuthenticatorStaticStageRequest
mkPatchedAuthenticatorStaticStageRequest =
  PatchedAuthenticatorStaticStageRequest
    { patchedAuthenticatorStaticStageRequestConfigureFlow = GHC.Maybe.Nothing,
      patchedAuthenticatorStaticStageRequestFlowSet = GHC.Maybe.Nothing,
      patchedAuthenticatorStaticStageRequestFriendlyName = GHC.Maybe.Nothing,
      patchedAuthenticatorStaticStageRequestName = GHC.Maybe.Nothing,
      patchedAuthenticatorStaticStageRequestTokenCount = GHC.Maybe.Nothing,
      patchedAuthenticatorStaticStageRequestTokenLength = GHC.Maybe.Nothing
    }
