module AuthentikAPI.Types.PermissionAssignRequest where
import qualified Data.Aeson
import qualified AuthentikAPI.Common
data PermissionAssignRequest
instance Show PermissionAssignRequest
instance Eq PermissionAssignRequest
instance Data.Aeson.FromJSON PermissionAssignRequest
instance Data.Aeson.ToJSON PermissionAssignRequest
