{-# LANGUAGE MultiWayIf #-}
-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.
{-# LANGUAGE OverloadedStrings #-}

-- | Contains the types generated from the schema PermissionAssignRequest
module AuthentikAPI.Types.PermissionAssignRequest where

import qualified AuthentikAPI.Common
import AuthentikAPI.TypeAlias
import {-# SOURCE #-} AuthentikAPI.Types.ModelEnum
import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Functor
import qualified Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe

-- | Defines the object schema located at @components.schemas.PermissionAssignRequest@ in the specification.
--
-- Request to assign a new permission
data PermissionAssignRequest = PermissionAssignRequest
  { -- | model
    permissionAssignRequestModel :: (GHC.Maybe.Maybe ModelEnum),
    -- | object_pk
    --
    -- Constraints:
    --
    -- * Minimum length of 1
    permissionAssignRequestObjectPk :: (GHC.Maybe.Maybe Data.Text.Internal.Text),
    -- | permissions
    permissionAssignRequestPermissions :: [Data.Text.Internal.Text]
  }
  deriving
    ( GHC.Show.Show,
      GHC.Classes.Eq
    )

instance Data.Aeson.Types.ToJSON.ToJSON PermissionAssignRequest where
  toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("model" Data.Aeson.Types.ToJSON..=)) (permissionAssignRequestModel obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("object_pk" Data.Aeson.Types.ToJSON..=)) (permissionAssignRequestObjectPk obj) : ["permissions" Data.Aeson.Types.ToJSON..= permissionAssignRequestPermissions obj] : GHC.Base.mempty))
  toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("model" Data.Aeson.Types.ToJSON..=)) (permissionAssignRequestModel obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("object_pk" Data.Aeson.Types.ToJSON..=)) (permissionAssignRequestObjectPk obj) : ["permissions" Data.Aeson.Types.ToJSON..= permissionAssignRequestPermissions obj] : GHC.Base.mempty)))

instance Data.Aeson.Types.FromJSON.FromJSON PermissionAssignRequest where
  parseJSON = Data.Aeson.Types.FromJSON.withObject "PermissionAssignRequest" (\obj -> ((GHC.Base.pure PermissionAssignRequest GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "model")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "object_pk")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "permissions"))

-- | Create a new 'PermissionAssignRequest' with all required fields.
mkPermissionAssignRequest ::
  -- | 'permissionAssignRequestPermissions'
  [Data.Text.Internal.Text] ->
  PermissionAssignRequest
mkPermissionAssignRequest permissionAssignRequestPermissions =
  PermissionAssignRequest
    { permissionAssignRequestModel = GHC.Maybe.Nothing,
      permissionAssignRequestObjectPk = GHC.Maybe.Nothing,
      permissionAssignRequestPermissions = permissionAssignRequestPermissions
    }
