module AuthentikAPI.Types.PlexSourcePropertyMappingRequest where
import qualified Data.Aeson
import qualified AuthentikAPI.Common
data PlexSourcePropertyMappingRequest
instance Show PlexSourcePropertyMappingRequest
instance Eq PlexSourcePropertyMappingRequest
instance Data.Aeson.FromJSON PlexSourcePropertyMappingRequest
instance Data.Aeson.ToJSON PlexSourcePropertyMappingRequest
