{-# LANGUAGE MultiWayIf #-}
-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.
{-# LANGUAGE OverloadedStrings #-}

-- | Contains the types generated from the schema PropertyMapping
module AuthentikAPI.Types.PropertyMapping where

import qualified AuthentikAPI.Common
import AuthentikAPI.TypeAlias
import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Functor
import qualified Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe

-- | Defines the object schema located at @components.schemas.PropertyMapping@ in the specification.
--
-- PropertyMapping Serializer
data PropertyMapping = PropertyMapping
  { -- | component: Get object\'s component so that we know how to edit the object
    propertyMappingComponent :: Data.Text.Internal.Text,
    -- | expression
    propertyMappingExpression :: Data.Text.Internal.Text,
    -- | managed: Objects that are managed by authentik. These objects are created and updated automatically. This flag only indicates that an object can be overwritten by migrations. You can still modify the objects via the API, but expect changes to be overwritten in a later update.
    propertyMappingManaged :: (GHC.Maybe.Maybe (AuthentikAPI.Common.Nullable Data.Text.Internal.Text)),
    -- | meta_model_name: Return internal model name
    propertyMappingMetaModelName :: Data.Text.Internal.Text,
    -- | name
    propertyMappingName :: Data.Text.Internal.Text,
    -- | pk
    propertyMappingPk :: Data.Text.Internal.Text,
    -- | verbose_name: Return object\'s verbose_name
    propertyMappingVerboseName :: Data.Text.Internal.Text,
    -- | verbose_name_plural: Return object\'s plural verbose_name
    propertyMappingVerboseNamePlural :: Data.Text.Internal.Text
  }
  deriving
    ( GHC.Show.Show,
      GHC.Classes.Eq
    )

instance Data.Aeson.Types.ToJSON.ToJSON PropertyMapping where
  toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (["component" Data.Aeson.Types.ToJSON..= propertyMappingComponent obj] : ["expression" Data.Aeson.Types.ToJSON..= propertyMappingExpression obj] : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("managed" Data.Aeson.Types.ToJSON..=)) (propertyMappingManaged obj) : ["meta_model_name" Data.Aeson.Types.ToJSON..= propertyMappingMetaModelName obj] : ["name" Data.Aeson.Types.ToJSON..= propertyMappingName obj] : ["pk" Data.Aeson.Types.ToJSON..= propertyMappingPk obj] : ["verbose_name" Data.Aeson.Types.ToJSON..= propertyMappingVerboseName obj] : ["verbose_name_plural" Data.Aeson.Types.ToJSON..= propertyMappingVerboseNamePlural obj] : GHC.Base.mempty))
  toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (["component" Data.Aeson.Types.ToJSON..= propertyMappingComponent obj] : ["expression" Data.Aeson.Types.ToJSON..= propertyMappingExpression obj] : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("managed" Data.Aeson.Types.ToJSON..=)) (propertyMappingManaged obj) : ["meta_model_name" Data.Aeson.Types.ToJSON..= propertyMappingMetaModelName obj] : ["name" Data.Aeson.Types.ToJSON..= propertyMappingName obj] : ["pk" Data.Aeson.Types.ToJSON..= propertyMappingPk obj] : ["verbose_name" Data.Aeson.Types.ToJSON..= propertyMappingVerboseName obj] : ["verbose_name_plural" Data.Aeson.Types.ToJSON..= propertyMappingVerboseNamePlural obj] : GHC.Base.mempty)))

instance Data.Aeson.Types.FromJSON.FromJSON PropertyMapping where
  parseJSON = Data.Aeson.Types.FromJSON.withObject "PropertyMapping" (\obj -> (((((((GHC.Base.pure PropertyMapping GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "component")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "expression")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "managed")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "meta_model_name")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "name")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "pk")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "verbose_name")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "verbose_name_plural"))

-- | Create a new 'PropertyMapping' with all required fields.
mkPropertyMapping ::
  -- | 'propertyMappingComponent'
  Data.Text.Internal.Text ->
  -- | 'propertyMappingExpression'
  Data.Text.Internal.Text ->
  -- | 'propertyMappingMetaModelName'
  Data.Text.Internal.Text ->
  -- | 'propertyMappingName'
  Data.Text.Internal.Text ->
  -- | 'propertyMappingPk'
  Data.Text.Internal.Text ->
  -- | 'propertyMappingVerboseName'
  Data.Text.Internal.Text ->
  -- | 'propertyMappingVerboseNamePlural'
  Data.Text.Internal.Text ->
  PropertyMapping
mkPropertyMapping propertyMappingComponent propertyMappingExpression propertyMappingMetaModelName propertyMappingName propertyMappingPk propertyMappingVerboseName propertyMappingVerboseNamePlural =
  PropertyMapping
    { propertyMappingComponent = propertyMappingComponent,
      propertyMappingExpression = propertyMappingExpression,
      propertyMappingManaged = GHC.Maybe.Nothing,
      propertyMappingMetaModelName = propertyMappingMetaModelName,
      propertyMappingName = propertyMappingName,
      propertyMappingPk = propertyMappingPk,
      propertyMappingVerboseName = propertyMappingVerboseName,
      propertyMappingVerboseNamePlural = propertyMappingVerboseNamePlural
    }
