{-# LANGUAGE MultiWayIf #-}
-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.
{-# LANGUAGE OverloadedStrings #-}

-- | Contains the types generated from the schema RadiusProviderPropertyMapping
module AuthentikAPI.Types.RadiusProviderPropertyMapping where

import qualified AuthentikAPI.Common
import AuthentikAPI.TypeAlias
import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Functor
import qualified Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe

-- | Defines the object schema located at @components.schemas.RadiusProviderPropertyMapping@ in the specification.
--
-- RadiusProviderPropertyMapping Serializer
data RadiusProviderPropertyMapping = RadiusProviderPropertyMapping
  { -- | component: Get object\'s component so that we know how to edit the object
    radiusProviderPropertyMappingComponent :: Data.Text.Internal.Text,
    -- | expression
    radiusProviderPropertyMappingExpression :: Data.Text.Internal.Text,
    -- | managed: Objects that are managed by authentik. These objects are created and updated automatically. This flag only indicates that an object can be overwritten by migrations. You can still modify the objects via the API, but expect changes to be overwritten in a later update.
    radiusProviderPropertyMappingManaged :: (GHC.Maybe.Maybe (AuthentikAPI.Common.Nullable Data.Text.Internal.Text)),
    -- | meta_model_name: Return internal model name
    radiusProviderPropertyMappingMetaModelName :: Data.Text.Internal.Text,
    -- | name
    radiusProviderPropertyMappingName :: Data.Text.Internal.Text,
    -- | pk
    radiusProviderPropertyMappingPk :: Data.Text.Internal.Text,
    -- | verbose_name: Return object\'s verbose_name
    radiusProviderPropertyMappingVerboseName :: Data.Text.Internal.Text,
    -- | verbose_name_plural: Return object\'s plural verbose_name
    radiusProviderPropertyMappingVerboseNamePlural :: Data.Text.Internal.Text
  }
  deriving
    ( GHC.Show.Show,
      GHC.Classes.Eq
    )

instance Data.Aeson.Types.ToJSON.ToJSON RadiusProviderPropertyMapping where
  toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (["component" Data.Aeson.Types.ToJSON..= radiusProviderPropertyMappingComponent obj] : ["expression" Data.Aeson.Types.ToJSON..= radiusProviderPropertyMappingExpression obj] : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("managed" Data.Aeson.Types.ToJSON..=)) (radiusProviderPropertyMappingManaged obj) : ["meta_model_name" Data.Aeson.Types.ToJSON..= radiusProviderPropertyMappingMetaModelName obj] : ["name" Data.Aeson.Types.ToJSON..= radiusProviderPropertyMappingName obj] : ["pk" Data.Aeson.Types.ToJSON..= radiusProviderPropertyMappingPk obj] : ["verbose_name" Data.Aeson.Types.ToJSON..= radiusProviderPropertyMappingVerboseName obj] : ["verbose_name_plural" Data.Aeson.Types.ToJSON..= radiusProviderPropertyMappingVerboseNamePlural obj] : GHC.Base.mempty))
  toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (["component" Data.Aeson.Types.ToJSON..= radiusProviderPropertyMappingComponent obj] : ["expression" Data.Aeson.Types.ToJSON..= radiusProviderPropertyMappingExpression obj] : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("managed" Data.Aeson.Types.ToJSON..=)) (radiusProviderPropertyMappingManaged obj) : ["meta_model_name" Data.Aeson.Types.ToJSON..= radiusProviderPropertyMappingMetaModelName obj] : ["name" Data.Aeson.Types.ToJSON..= radiusProviderPropertyMappingName obj] : ["pk" Data.Aeson.Types.ToJSON..= radiusProviderPropertyMappingPk obj] : ["verbose_name" Data.Aeson.Types.ToJSON..= radiusProviderPropertyMappingVerboseName obj] : ["verbose_name_plural" Data.Aeson.Types.ToJSON..= radiusProviderPropertyMappingVerboseNamePlural obj] : GHC.Base.mempty)))

instance Data.Aeson.Types.FromJSON.FromJSON RadiusProviderPropertyMapping where
  parseJSON = Data.Aeson.Types.FromJSON.withObject "RadiusProviderPropertyMapping" (\obj -> (((((((GHC.Base.pure RadiusProviderPropertyMapping GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "component")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "expression")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "managed")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "meta_model_name")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "name")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "pk")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "verbose_name")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "verbose_name_plural"))

-- | Create a new 'RadiusProviderPropertyMapping' with all required fields.
mkRadiusProviderPropertyMapping ::
  -- | 'radiusProviderPropertyMappingComponent'
  Data.Text.Internal.Text ->
  -- | 'radiusProviderPropertyMappingExpression'
  Data.Text.Internal.Text ->
  -- | 'radiusProviderPropertyMappingMetaModelName'
  Data.Text.Internal.Text ->
  -- | 'radiusProviderPropertyMappingName'
  Data.Text.Internal.Text ->
  -- | 'radiusProviderPropertyMappingPk'
  Data.Text.Internal.Text ->
  -- | 'radiusProviderPropertyMappingVerboseName'
  Data.Text.Internal.Text ->
  -- | 'radiusProviderPropertyMappingVerboseNamePlural'
  Data.Text.Internal.Text ->
  RadiusProviderPropertyMapping
mkRadiusProviderPropertyMapping radiusProviderPropertyMappingComponent radiusProviderPropertyMappingExpression radiusProviderPropertyMappingMetaModelName radiusProviderPropertyMappingName radiusProviderPropertyMappingPk radiusProviderPropertyMappingVerboseName radiusProviderPropertyMappingVerboseNamePlural =
  RadiusProviderPropertyMapping
    { radiusProviderPropertyMappingComponent = radiusProviderPropertyMappingComponent,
      radiusProviderPropertyMappingExpression = radiusProviderPropertyMappingExpression,
      radiusProviderPropertyMappingManaged = GHC.Maybe.Nothing,
      radiusProviderPropertyMappingMetaModelName = radiusProviderPropertyMappingMetaModelName,
      radiusProviderPropertyMappingName = radiusProviderPropertyMappingName,
      radiusProviderPropertyMappingPk = radiusProviderPropertyMappingPk,
      radiusProviderPropertyMappingVerboseName = radiusProviderPropertyMappingVerboseName,
      radiusProviderPropertyMappingVerboseNamePlural = radiusProviderPropertyMappingVerboseNamePlural
    }
