{-# LANGUAGE MultiWayIf #-}
-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.
{-# LANGUAGE OverloadedStrings #-}

-- | Contains the types generated from the schema RadiusOutpostConfig
module AuthentikAPI.Types.RadiusOutpostConfig where

import qualified AuthentikAPI.Common
import AuthentikAPI.TypeAlias
import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Functor
import qualified Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe

-- | Defines the object schema located at @components.schemas.RadiusOutpostConfig@ in the specification.
--
-- RadiusProvider Serializer
data RadiusOutpostConfig = RadiusOutpostConfig
  { -- | application_slug
    radiusOutpostConfigApplicationSlug :: Data.Text.Internal.Text,
    -- | auth_flow_slug
    radiusOutpostConfigAuthFlowSlug :: Data.Text.Internal.Text,
    -- | client_networks: List of CIDRs (comma-separated) that clients can connect from. A more specific CIDR will match before a looser one. Clients connecting from a non-specified CIDR will be dropped.
    radiusOutpostConfigClientNetworks :: (GHC.Maybe.Maybe Data.Text.Internal.Text),
    -- | mfa_support: When enabled, code-based multi-factor authentication can be used by appending a semicolon and the TOTP code to the password. This should only be enabled if all users that will bind to this provider have a TOTP device configured, as otherwise a password may incorrectly be rejected if it contains a semicolon.
    radiusOutpostConfigMfaSupport :: (GHC.Maybe.Maybe GHC.Types.Bool),
    -- | name
    radiusOutpostConfigName :: Data.Text.Internal.Text,
    -- | pk
    radiusOutpostConfigPk :: GHC.Types.Int,
    -- | shared_secret: Shared secret between clients and server to hash packets.
    radiusOutpostConfigSharedSecret :: (GHC.Maybe.Maybe Data.Text.Internal.Text)
  }
  deriving
    ( GHC.Show.Show,
      GHC.Classes.Eq
    )

instance Data.Aeson.Types.ToJSON.ToJSON RadiusOutpostConfig where
  toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (["application_slug" Data.Aeson.Types.ToJSON..= radiusOutpostConfigApplicationSlug obj] : ["auth_flow_slug" Data.Aeson.Types.ToJSON..= radiusOutpostConfigAuthFlowSlug obj] : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("client_networks" Data.Aeson.Types.ToJSON..=)) (radiusOutpostConfigClientNetworks obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("mfa_support" Data.Aeson.Types.ToJSON..=)) (radiusOutpostConfigMfaSupport obj) : ["name" Data.Aeson.Types.ToJSON..= radiusOutpostConfigName obj] : ["pk" Data.Aeson.Types.ToJSON..= radiusOutpostConfigPk obj] : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("shared_secret" Data.Aeson.Types.ToJSON..=)) (radiusOutpostConfigSharedSecret obj) : GHC.Base.mempty))
  toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (["application_slug" Data.Aeson.Types.ToJSON..= radiusOutpostConfigApplicationSlug obj] : ["auth_flow_slug" Data.Aeson.Types.ToJSON..= radiusOutpostConfigAuthFlowSlug obj] : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("client_networks" Data.Aeson.Types.ToJSON..=)) (radiusOutpostConfigClientNetworks obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("mfa_support" Data.Aeson.Types.ToJSON..=)) (radiusOutpostConfigMfaSupport obj) : ["name" Data.Aeson.Types.ToJSON..= radiusOutpostConfigName obj] : ["pk" Data.Aeson.Types.ToJSON..= radiusOutpostConfigPk obj] : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("shared_secret" Data.Aeson.Types.ToJSON..=)) (radiusOutpostConfigSharedSecret obj) : GHC.Base.mempty)))

instance Data.Aeson.Types.FromJSON.FromJSON RadiusOutpostConfig where
  parseJSON = Data.Aeson.Types.FromJSON.withObject "RadiusOutpostConfig" (\obj -> ((((((GHC.Base.pure RadiusOutpostConfig GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "application_slug")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "auth_flow_slug")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "client_networks")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "mfa_support")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "name")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "pk")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "shared_secret"))

-- | Create a new 'RadiusOutpostConfig' with all required fields.
mkRadiusOutpostConfig ::
  -- | 'radiusOutpostConfigApplicationSlug'
  Data.Text.Internal.Text ->
  -- | 'radiusOutpostConfigAuthFlowSlug'
  Data.Text.Internal.Text ->
  -- | 'radiusOutpostConfigName'
  Data.Text.Internal.Text ->
  -- | 'radiusOutpostConfigPk'
  GHC.Types.Int ->
  RadiusOutpostConfig
mkRadiusOutpostConfig radiusOutpostConfigApplicationSlug radiusOutpostConfigAuthFlowSlug radiusOutpostConfigName radiusOutpostConfigPk =
  RadiusOutpostConfig
    { radiusOutpostConfigApplicationSlug = radiusOutpostConfigApplicationSlug,
      radiusOutpostConfigAuthFlowSlug = radiusOutpostConfigAuthFlowSlug,
      radiusOutpostConfigClientNetworks = GHC.Maybe.Nothing,
      radiusOutpostConfigMfaSupport = GHC.Maybe.Nothing,
      radiusOutpostConfigName = radiusOutpostConfigName,
      radiusOutpostConfigPk = radiusOutpostConfigPk,
      radiusOutpostConfigSharedSecret = GHC.Maybe.Nothing
    }
