{-# LANGUAGE MultiWayIf #-}
-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.
{-# LANGUAGE OverloadedStrings #-}

-- | Contains the types generated from the schema SCIMSourcePropertyMappingRequest
module AuthentikAPI.Types.SCIMSourcePropertyMappingRequest where

import qualified AuthentikAPI.Common
import AuthentikAPI.TypeAlias
import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Functor
import qualified Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe

-- | Defines the object schema located at @components.schemas.SCIMSourcePropertyMappingRequest@ in the specification.
--
-- SCIMSourcePropertyMapping Serializer
data SCIMSourcePropertyMappingRequest = SCIMSourcePropertyMappingRequest
  { -- | expression
    --
    -- Constraints:
    --
    -- * Minimum length of 1
    sCIMSourcePropertyMappingRequestExpression :: Data.Text.Internal.Text,
    -- | managed: Objects that are managed by authentik. These objects are created and updated automatically. This flag only indicates that an object can be overwritten by migrations. You can still modify the objects via the API, but expect changes to be overwritten in a later update.
    --
    -- Constraints:
    --
    -- * Minimum length of 1
    sCIMSourcePropertyMappingRequestManaged :: (GHC.Maybe.Maybe (AuthentikAPI.Common.Nullable Data.Text.Internal.Text)),
    -- | name
    --
    -- Constraints:
    --
    -- * Minimum length of 1
    sCIMSourcePropertyMappingRequestName :: Data.Text.Internal.Text
  }
  deriving
    ( GHC.Show.Show,
      GHC.Classes.Eq
    )

instance Data.Aeson.Types.ToJSON.ToJSON SCIMSourcePropertyMappingRequest where
  toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (["expression" Data.Aeson.Types.ToJSON..= sCIMSourcePropertyMappingRequestExpression obj] : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("managed" Data.Aeson.Types.ToJSON..=)) (sCIMSourcePropertyMappingRequestManaged obj) : ["name" Data.Aeson.Types.ToJSON..= sCIMSourcePropertyMappingRequestName obj] : GHC.Base.mempty))
  toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (["expression" Data.Aeson.Types.ToJSON..= sCIMSourcePropertyMappingRequestExpression obj] : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("managed" Data.Aeson.Types.ToJSON..=)) (sCIMSourcePropertyMappingRequestManaged obj) : ["name" Data.Aeson.Types.ToJSON..= sCIMSourcePropertyMappingRequestName obj] : GHC.Base.mempty)))

instance Data.Aeson.Types.FromJSON.FromJSON SCIMSourcePropertyMappingRequest where
  parseJSON = Data.Aeson.Types.FromJSON.withObject "SCIMSourcePropertyMappingRequest" (\obj -> ((GHC.Base.pure SCIMSourcePropertyMappingRequest GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "expression")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "managed")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "name"))

-- | Create a new 'SCIMSourcePropertyMappingRequest' with all required fields.
mkSCIMSourcePropertyMappingRequest ::
  -- | 'sCIMSourcePropertyMappingRequestExpression'
  Data.Text.Internal.Text ->
  -- | 'sCIMSourcePropertyMappingRequestName'
  Data.Text.Internal.Text ->
  SCIMSourcePropertyMappingRequest
mkSCIMSourcePropertyMappingRequest sCIMSourcePropertyMappingRequestExpression sCIMSourcePropertyMappingRequestName =
  SCIMSourcePropertyMappingRequest
    { sCIMSourcePropertyMappingRequestExpression = sCIMSourcePropertyMappingRequestExpression,
      sCIMSourcePropertyMappingRequestManaged = GHC.Maybe.Nothing,
      sCIMSourcePropertyMappingRequestName = sCIMSourcePropertyMappingRequestName
    }
