{-# LANGUAGE MultiWayIf #-}
-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.
{-# LANGUAGE OverloadedStrings #-}

-- | Contains the types generated from the schema StaticDevice
module AuthentikAPI.Types.StaticDevice where

import qualified AuthentikAPI.Common
import AuthentikAPI.TypeAlias
import {-# SOURCE #-} AuthentikAPI.Types.GroupMember
import {-# SOURCE #-} AuthentikAPI.Types.StaticDeviceToken
import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Functor
import qualified Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe

-- | Defines the object schema located at @components.schemas.StaticDevice@ in the specification.
--
-- Serializer for static authenticator devices
data StaticDevice = StaticDevice
  { -- | name: The human-readable name of this device.
    --
    -- Constraints:
    --
    -- * Maximum length of 64
    staticDeviceName :: Data.Text.Internal.Text,
    -- | pk
    staticDevicePk :: GHC.Types.Int,
    -- | token_set
    staticDeviceTokenSet :: [StaticDeviceToken],
    -- | user
    staticDeviceUser :: StaticDeviceUser'
  }
  deriving
    ( GHC.Show.Show,
      GHC.Classes.Eq
    )

instance Data.Aeson.Types.ToJSON.ToJSON StaticDevice where
  toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (["name" Data.Aeson.Types.ToJSON..= staticDeviceName obj] : ["pk" Data.Aeson.Types.ToJSON..= staticDevicePk obj] : ["token_set" Data.Aeson.Types.ToJSON..= staticDeviceTokenSet obj] : ["user" Data.Aeson.Types.ToJSON..= staticDeviceUser obj] : GHC.Base.mempty))
  toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (["name" Data.Aeson.Types.ToJSON..= staticDeviceName obj] : ["pk" Data.Aeson.Types.ToJSON..= staticDevicePk obj] : ["token_set" Data.Aeson.Types.ToJSON..= staticDeviceTokenSet obj] : ["user" Data.Aeson.Types.ToJSON..= staticDeviceUser obj] : GHC.Base.mempty)))

instance Data.Aeson.Types.FromJSON.FromJSON StaticDevice where
  parseJSON = Data.Aeson.Types.FromJSON.withObject "StaticDevice" (\obj -> (((GHC.Base.pure StaticDevice GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "name")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "pk")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "token_set")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "user"))

-- | Create a new 'StaticDevice' with all required fields.
mkStaticDevice ::
  -- | 'staticDeviceName'
  Data.Text.Internal.Text ->
  -- | 'staticDevicePk'
  GHC.Types.Int ->
  -- | 'staticDeviceTokenSet'
  [StaticDeviceToken] ->
  -- | 'staticDeviceUser'
  StaticDeviceUser' ->
  StaticDevice
mkStaticDevice staticDeviceName staticDevicePk staticDeviceTokenSet staticDeviceUser =
  StaticDevice
    { staticDeviceName = staticDeviceName,
      staticDevicePk = staticDevicePk,
      staticDeviceTokenSet = staticDeviceTokenSet,
      staticDeviceUser = staticDeviceUser
    }

-- | Defines the object schema located at @components.schemas.StaticDevice.properties.user.allOf@ in the specification.
data StaticDeviceUser' = StaticDeviceUser'
  { -- | attributes
    staticDeviceUser'Attributes :: (GHC.Maybe.Maybe Data.Aeson.Types.Internal.Object),
    -- | email
    --
    -- Constraints:
    --
    -- * Maximum length of 254
    staticDeviceUser'Email :: (GHC.Maybe.Maybe Data.Text.Internal.Text),
    -- | is_active: Designates whether this user should be treated as active. Unselect this instead of deleting accounts.
    staticDeviceUser'IsActive :: (GHC.Maybe.Maybe GHC.Types.Bool),
    -- | last_login
    staticDeviceUser'LastLogin :: (GHC.Maybe.Maybe (AuthentikAPI.Common.Nullable Data.Text.Internal.Text)),
    -- | name: User\'s display name.
    staticDeviceUser'Name :: Data.Text.Internal.Text,
    -- | pk
    staticDeviceUser'Pk :: GHC.Types.Int,
    -- | uid
    staticDeviceUser'Uid :: Data.Text.Internal.Text,
    -- | username: Required. 150 characters or fewer. Letters, digits and \@\/.\/+\/-\/_ only.
    --
    -- Constraints:
    --
    -- * Maximum length of 150
    -- * Must match pattern \'^[\\w.\@+-]+\$\'
    staticDeviceUser'Username :: Data.Text.Internal.Text
  }
  deriving
    ( GHC.Show.Show,
      GHC.Classes.Eq
    )

instance Data.Aeson.Types.ToJSON.ToJSON StaticDeviceUser' where
  toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("attributes" Data.Aeson.Types.ToJSON..=)) (staticDeviceUser'Attributes obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("email" Data.Aeson.Types.ToJSON..=)) (staticDeviceUser'Email obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("is_active" Data.Aeson.Types.ToJSON..=)) (staticDeviceUser'IsActive obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("last_login" Data.Aeson.Types.ToJSON..=)) (staticDeviceUser'LastLogin obj) : ["name" Data.Aeson.Types.ToJSON..= staticDeviceUser'Name obj] : ["pk" Data.Aeson.Types.ToJSON..= staticDeviceUser'Pk obj] : ["uid" Data.Aeson.Types.ToJSON..= staticDeviceUser'Uid obj] : ["username" Data.Aeson.Types.ToJSON..= staticDeviceUser'Username obj] : GHC.Base.mempty))
  toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("attributes" Data.Aeson.Types.ToJSON..=)) (staticDeviceUser'Attributes obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("email" Data.Aeson.Types.ToJSON..=)) (staticDeviceUser'Email obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("is_active" Data.Aeson.Types.ToJSON..=)) (staticDeviceUser'IsActive obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("last_login" Data.Aeson.Types.ToJSON..=)) (staticDeviceUser'LastLogin obj) : ["name" Data.Aeson.Types.ToJSON..= staticDeviceUser'Name obj] : ["pk" Data.Aeson.Types.ToJSON..= staticDeviceUser'Pk obj] : ["uid" Data.Aeson.Types.ToJSON..= staticDeviceUser'Uid obj] : ["username" Data.Aeson.Types.ToJSON..= staticDeviceUser'Username obj] : GHC.Base.mempty)))

instance Data.Aeson.Types.FromJSON.FromJSON StaticDeviceUser' where
  parseJSON = Data.Aeson.Types.FromJSON.withObject "StaticDeviceUser'" (\obj -> (((((((GHC.Base.pure StaticDeviceUser' GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "attributes")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "email")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "is_active")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "last_login")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "name")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "pk")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "uid")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "username"))

-- | Create a new 'StaticDeviceUser'' with all required fields.
mkStaticDeviceUser' ::
  -- | 'staticDeviceUser'Name'
  Data.Text.Internal.Text ->
  -- | 'staticDeviceUser'Pk'
  GHC.Types.Int ->
  -- | 'staticDeviceUser'Uid'
  Data.Text.Internal.Text ->
  -- | 'staticDeviceUser'Username'
  Data.Text.Internal.Text ->
  StaticDeviceUser'
mkStaticDeviceUser' staticDeviceUser'Name staticDeviceUser'Pk staticDeviceUser'Uid staticDeviceUser'Username =
  StaticDeviceUser'
    { staticDeviceUser'Attributes = GHC.Maybe.Nothing,
      staticDeviceUser'Email = GHC.Maybe.Nothing,
      staticDeviceUser'IsActive = GHC.Maybe.Nothing,
      staticDeviceUser'LastLogin = GHC.Maybe.Nothing,
      staticDeviceUser'Name = staticDeviceUser'Name,
      staticDeviceUser'Pk = staticDeviceUser'Pk,
      staticDeviceUser'Uid = staticDeviceUser'Uid,
      staticDeviceUser'Username = staticDeviceUser'Username
    }
