module AuthentikAPI.Types.TenantAdminGroupRequestRequest where
import qualified Data.Aeson
import qualified AuthentikAPI.Common
data TenantAdminGroupRequestRequest
instance Show TenantAdminGroupRequestRequest
instance Eq TenantAdminGroupRequestRequest
instance Data.Aeson.FromJSON TenantAdminGroupRequestRequest
instance Data.Aeson.ToJSON TenantAdminGroupRequestRequest
