module AuthentikAPI.Types.UserPlexSourceConnectionRequest where
import qualified Data.Aeson
import qualified AuthentikAPI.Common
data UserPlexSourceConnectionRequest
instance Show UserPlexSourceConnectionRequest
instance Eq UserPlexSourceConnectionRequest
instance Data.Aeson.FromJSON UserPlexSourceConnectionRequest
instance Data.Aeson.ToJSON UserPlexSourceConnectionRequest
