{-# LANGUAGE ExplicitForAll #-}
{-# LANGUAGE MultiWayIf #-}
-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.
{-# LANGUAGE OverloadedStrings #-}

-- | Contains the different functions to run the operation providersGoogleWorkspaceList
module AuthentikAPI.Operations.ProvidersGoogleWorkspaceList where

import qualified AuthentikAPI.Common
import AuthentikAPI.Types
import qualified Control.Monad.Fail
import qualified Control.Monad.Trans.Reader
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.ByteString as Data.ByteString.Internal.Type
import qualified Data.Either
import qualified Data.Foldable
import qualified Data.Functor
import qualified Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified Data.Vector
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified Network.HTTP.Client
import qualified Network.HTTP.Client as Network.HTTP.Client.Request
import qualified Network.HTTP.Client as Network.HTTP.Client.Types
import qualified Network.HTTP.Simple
import qualified Network.HTTP.Types
import qualified Network.HTTP.Types as Network.HTTP.Types.Status
import qualified Network.HTTP.Types as Network.HTTP.Types.URI
import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe

-- | > GET /providers/google_workspace/
--
-- GoogleWorkspaceProvider Viewset
providersGoogleWorkspaceList ::
  forall m.
  (AuthentikAPI.Common.MonadHTTP m) =>
  -- | Contains all available parameters of this operation (query and path parameters)
  ProvidersGoogleWorkspaceListParameters ->
  -- | Monadic computation which returns the result of the operation
  AuthentikAPI.Common.ClientT m (Network.HTTP.Client.Types.Response ProvidersGoogleWorkspaceListResponse)
providersGoogleWorkspaceList parameters =
  GHC.Base.fmap
    ( \response_0 ->
        GHC.Base.fmap
          ( Data.Either.either ProvidersGoogleWorkspaceListResponseError GHC.Base.id
              GHC.Base.. ( \response body ->
                             if
                               | (\status_1 -> Network.HTTP.Types.Status.statusCode status_1 GHC.Classes.== 200) (Network.HTTP.Client.Types.responseStatus response) ->
                                   ProvidersGoogleWorkspaceListResponse200
                                     Data.Functor.<$> ( Data.Aeson.eitherDecodeStrict body ::
                                                          Data.Either.Either
                                                            GHC.Base.String
                                                            PaginatedGoogleWorkspaceProviderList
                                                      )
                               | (\status_2 -> Network.HTTP.Types.Status.statusCode status_2 GHC.Classes.== 400) (Network.HTTP.Client.Types.responseStatus response) ->
                                   ProvidersGoogleWorkspaceListResponse400
                                     Data.Functor.<$> ( Data.Aeson.eitherDecodeStrict body ::
                                                          Data.Either.Either
                                                            GHC.Base.String
                                                            ValidationError
                                                      )
                               | (\status_3 -> Network.HTTP.Types.Status.statusCode status_3 GHC.Classes.== 403) (Network.HTTP.Client.Types.responseStatus response) ->
                                   ProvidersGoogleWorkspaceListResponse403
                                     Data.Functor.<$> ( Data.Aeson.eitherDecodeStrict body ::
                                                          Data.Either.Either
                                                            GHC.Base.String
                                                            GenericError
                                                      )
                               | GHC.Base.otherwise -> Data.Either.Left "Missing default response type"
                         )
                response_0
          )
          response_0
    )
    ( AuthentikAPI.Common.doCallWithConfigurationM
        (Data.Text.toUpper GHC.Base.$ Data.Text.Internal.pack "GET")
        "/providers/google_workspace/"
        [ AuthentikAPI.Common.QueryParameter (Data.Text.Internal.pack "delegated_subject") (Data.Aeson.Types.ToJSON.toJSON Data.Functor.<$> providersGoogleWorkspaceListParametersQueryDelegatedSubject parameters) (Data.Text.Internal.pack "form") GHC.Types.False,
          AuthentikAPI.Common.QueryParameter (Data.Text.Internal.pack "exclude_users_service_account") (Data.Aeson.Types.ToJSON.toJSON Data.Functor.<$> providersGoogleWorkspaceListParametersQueryExcludeUsersServiceAccount parameters) (Data.Text.Internal.pack "form") GHC.Types.False,
          AuthentikAPI.Common.QueryParameter (Data.Text.Internal.pack "filter_group") (Data.Aeson.Types.ToJSON.toJSON Data.Functor.<$> providersGoogleWorkspaceListParametersQueryFilterGroup parameters) (Data.Text.Internal.pack "form") GHC.Types.False,
          AuthentikAPI.Common.QueryParameter (Data.Text.Internal.pack "name") (Data.Aeson.Types.ToJSON.toJSON Data.Functor.<$> providersGoogleWorkspaceListParametersQueryName parameters) (Data.Text.Internal.pack "form") GHC.Types.False,
          AuthentikAPI.Common.QueryParameter (Data.Text.Internal.pack "ordering") (Data.Aeson.Types.ToJSON.toJSON Data.Functor.<$> providersGoogleWorkspaceListParametersQueryOrdering parameters) (Data.Text.Internal.pack "form") GHC.Types.False,
          AuthentikAPI.Common.QueryParameter (Data.Text.Internal.pack "page") (Data.Aeson.Types.ToJSON.toJSON Data.Functor.<$> providersGoogleWorkspaceListParametersQueryPage parameters) (Data.Text.Internal.pack "form") GHC.Types.False,
          AuthentikAPI.Common.QueryParameter (Data.Text.Internal.pack "page_size") (Data.Aeson.Types.ToJSON.toJSON Data.Functor.<$> providersGoogleWorkspaceListParametersQueryPageSize parameters) (Data.Text.Internal.pack "form") GHC.Types.False,
          AuthentikAPI.Common.QueryParameter (Data.Text.Internal.pack "search") (Data.Aeson.Types.ToJSON.toJSON Data.Functor.<$> providersGoogleWorkspaceListParametersQuerySearch parameters) (Data.Text.Internal.pack "form") GHC.Types.False
        ]
    )

-- | Defines the object schema located at @paths.\/providers\/google_workspace\/.GET.parameters@ in the specification.
data ProvidersGoogleWorkspaceListParameters = ProvidersGoogleWorkspaceListParameters
  { -- | queryDelegated_subject: Represents the parameter named \'delegated_subject\'
    providersGoogleWorkspaceListParametersQueryDelegatedSubject :: (GHC.Maybe.Maybe Data.Text.Internal.Text),
    -- | queryExclude_users_service_account: Represents the parameter named \'exclude_users_service_account\'
    providersGoogleWorkspaceListParametersQueryExcludeUsersServiceAccount :: (GHC.Maybe.Maybe GHC.Types.Bool),
    -- | queryFilter_group: Represents the parameter named \'filter_group\'
    providersGoogleWorkspaceListParametersQueryFilterGroup :: (GHC.Maybe.Maybe Data.Text.Internal.Text),
    -- | queryName: Represents the parameter named \'name\'
    providersGoogleWorkspaceListParametersQueryName :: (GHC.Maybe.Maybe Data.Text.Internal.Text),
    -- | queryOrdering: Represents the parameter named \'ordering\'
    --
    -- Which field to use when ordering the results.
    providersGoogleWorkspaceListParametersQueryOrdering :: (GHC.Maybe.Maybe Data.Text.Internal.Text),
    -- | queryPage: Represents the parameter named \'page\'
    --
    -- A page number within the paginated result set.
    providersGoogleWorkspaceListParametersQueryPage :: (GHC.Maybe.Maybe GHC.Types.Int),
    -- | queryPage_size: Represents the parameter named \'page_size\'
    --
    -- Number of results to return per page.
    providersGoogleWorkspaceListParametersQueryPageSize :: (GHC.Maybe.Maybe GHC.Types.Int),
    -- | querySearch: Represents the parameter named \'search\'
    --
    -- A search term.
    providersGoogleWorkspaceListParametersQuerySearch :: (GHC.Maybe.Maybe Data.Text.Internal.Text)
  }
  deriving
    ( GHC.Show.Show,
      GHC.Classes.Eq
    )

instance Data.Aeson.Types.ToJSON.ToJSON ProvidersGoogleWorkspaceListParameters where
  toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("queryDelegated_subject" Data.Aeson.Types.ToJSON..=)) (providersGoogleWorkspaceListParametersQueryDelegatedSubject obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("queryExclude_users_service_account" Data.Aeson.Types.ToJSON..=)) (providersGoogleWorkspaceListParametersQueryExcludeUsersServiceAccount obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("queryFilter_group" Data.Aeson.Types.ToJSON..=)) (providersGoogleWorkspaceListParametersQueryFilterGroup obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("queryName" Data.Aeson.Types.ToJSON..=)) (providersGoogleWorkspaceListParametersQueryName obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("queryOrdering" Data.Aeson.Types.ToJSON..=)) (providersGoogleWorkspaceListParametersQueryOrdering obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("queryPage" Data.Aeson.Types.ToJSON..=)) (providersGoogleWorkspaceListParametersQueryPage obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("queryPage_size" Data.Aeson.Types.ToJSON..=)) (providersGoogleWorkspaceListParametersQueryPageSize obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("querySearch" Data.Aeson.Types.ToJSON..=)) (providersGoogleWorkspaceListParametersQuerySearch obj) : GHC.Base.mempty))
  toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("queryDelegated_subject" Data.Aeson.Types.ToJSON..=)) (providersGoogleWorkspaceListParametersQueryDelegatedSubject obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("queryExclude_users_service_account" Data.Aeson.Types.ToJSON..=)) (providersGoogleWorkspaceListParametersQueryExcludeUsersServiceAccount obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("queryFilter_group" Data.Aeson.Types.ToJSON..=)) (providersGoogleWorkspaceListParametersQueryFilterGroup obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("queryName" Data.Aeson.Types.ToJSON..=)) (providersGoogleWorkspaceListParametersQueryName obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("queryOrdering" Data.Aeson.Types.ToJSON..=)) (providersGoogleWorkspaceListParametersQueryOrdering obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("queryPage" Data.Aeson.Types.ToJSON..=)) (providersGoogleWorkspaceListParametersQueryPage obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("queryPage_size" Data.Aeson.Types.ToJSON..=)) (providersGoogleWorkspaceListParametersQueryPageSize obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("querySearch" Data.Aeson.Types.ToJSON..=)) (providersGoogleWorkspaceListParametersQuerySearch obj) : GHC.Base.mempty)))

instance Data.Aeson.Types.FromJSON.FromJSON ProvidersGoogleWorkspaceListParameters where
  parseJSON = Data.Aeson.Types.FromJSON.withObject "ProvidersGoogleWorkspaceListParameters" (\obj -> (((((((GHC.Base.pure ProvidersGoogleWorkspaceListParameters GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "queryDelegated_subject")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "queryExclude_users_service_account")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "queryFilter_group")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "queryName")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "queryOrdering")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "queryPage")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "queryPage_size")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "querySearch"))

-- | Create a new 'ProvidersGoogleWorkspaceListParameters' with all required fields.
mkProvidersGoogleWorkspaceListParameters :: ProvidersGoogleWorkspaceListParameters
mkProvidersGoogleWorkspaceListParameters =
  ProvidersGoogleWorkspaceListParameters
    { providersGoogleWorkspaceListParametersQueryDelegatedSubject = GHC.Maybe.Nothing,
      providersGoogleWorkspaceListParametersQueryExcludeUsersServiceAccount = GHC.Maybe.Nothing,
      providersGoogleWorkspaceListParametersQueryFilterGroup = GHC.Maybe.Nothing,
      providersGoogleWorkspaceListParametersQueryName = GHC.Maybe.Nothing,
      providersGoogleWorkspaceListParametersQueryOrdering = GHC.Maybe.Nothing,
      providersGoogleWorkspaceListParametersQueryPage = GHC.Maybe.Nothing,
      providersGoogleWorkspaceListParametersQueryPageSize = GHC.Maybe.Nothing,
      providersGoogleWorkspaceListParametersQuerySearch = GHC.Maybe.Nothing
    }

-- | Represents a response of the operation 'providersGoogleWorkspaceList'.
--
-- The response constructor is chosen by the status code of the response. If no case matches (no specific case for the response code, no range case, no default case), 'ProvidersGoogleWorkspaceListResponseError' is used.
data ProvidersGoogleWorkspaceListResponse
  = -- | Means either no matching case available or a parse error
    ProvidersGoogleWorkspaceListResponseError GHC.Base.String
  | ProvidersGoogleWorkspaceListResponse200 PaginatedGoogleWorkspaceProviderList
  | ProvidersGoogleWorkspaceListResponse400 ValidationError
  | ProvidersGoogleWorkspaceListResponse403 GenericError
  deriving (GHC.Show.Show, GHC.Classes.Eq)
