name: Build 
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  biuld:
    name: Build 
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            substituters = https://${{ secrets.CACHE_NAME }}.nyc3.cdn.digitaloceanspaces.com https://cache.nixos.org/ 
            trusted-public-keys = ${{ secrets.CACHE_NAME }}:8DAGzkp4auED3kD0b5ahCOYyXwcmsq9xpTCshlGai50= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= 

      - name: Build Applications
        run: |
          nix build .#authentik-hs --no-link --print-out-paths

